In [1]:
import pandas as pd
import matplotlib as plt
import numpy as np
%matplotlib inline

In [26]:
pd.set_option('display.max_rows', 1000)

# Load Data

In [5]:
community_health = pd.read_csv(r'data/Datathon Materials/community_health.csv')
community_health.head()

,county_name,health_topic,indicator,event_count,avg_num_of_denominator,unit_measurement,precent_or_rate,low_limit_95p_CI,upp_limit_95p_CI,data_comment,year,data_source,lat_long
0,Albany,Family Planning/Natality Indicators,Percentage of births within 24 months of previ...,2043.0,3144.0,Percentage,21.7,NaN,NaN,NaN,2012-2014,"2012-2014 Vital Statistics Data as of May, 2016","(42.678066, -73.814233)"
1,Allegany,Family Planning/Natality Indicators,Percentage of births within 24 months of previ...,399.0,487.0,Percentage,27.3,NaN,NaN,NaN,2012-2014,"2012-2014 Vital Statistics Data as of May, 2016","(42.226801, -78.020567)"
2,Bronx,Family Planning/Natality Indicators,Percentage of births within 24 months of previ...,10032.0,21249.0,Percentage,15.7,NaN,NaN,NaN,2012-2014,"2012-2014 Vital Statistics Data as of May, 2016","(40.85589, -73.868294)"
3,Broome,Family Planning/Natality Indicators,Percentage of births within 24 months of previ...,1654.0,2083.0,Percentage,26.5,NaN,NaN,NaN,2012-2014,"2012-2014 Vital Statistics Data as of May, 2016","(42.122015, -75.933191)"
4,Capital Region,Family Planning/Natality Indicators,Percentage of births within 24 months of previ...,6273.0,9774.0,Percentage,21.4,NaN,NaN,NaN,2012-2014,"2012-2014 Vital Statistics Data as of May, 2016",NaN

In [6]:
service_requests = pd.read_csv(r'data/Datathon Materials/311_service_requests.csv')
service_requests.head()

C:\Users\nicol\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,unique_key,created_date,closed_date,agency_acronym,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,street_name,city,status,due_date,resolution_date,community_board,borough,latitude,longitude
0,28272192,06/16/2014 09:34:00 AM,06/16/2014 12:00:00 PM,DSNY,BCC - Brooklyn South,Sanitation Condition,15 Street Cond/Dump-Out/Drop-Off,Street,11232,218 31 STREET,31 STREET,BROOKLYN,Closed,NaN,06/16/2014 12:00:00 PM,07 BROOKLYN,BROOKLYN,40.656066,-73.999805
1,28272281,06/16/2014 08:21:00 AM,06/16/2014 12:00:00 PM,DSNY,BCC - Brooklyn South,Sanitation Condition,15 Street Cond/Dump-Out/Drop-Off,Street,11234,5207 AVENUE T,AVENUE T,BROOKLYN,Closed,NaN,06/16/2014 12:00:00 PM,18 BROOKLYN,BROOKLYN,40.611781,-73.923889
2,28272228,06/16/2014 12:00:00 AM,07/15/2014 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,1-2 Family Dwelling,11209,230 94 STREET,94 STREET,BROOKLYN,Closed,07/16/2014 12:13:55 PM,07/15/2014 12:00:00 AM,10 BROOKLYN,BROOKLYN,40.618345,-74.034990
3,28272229,06/16/2014 12:00:00 AM,07/01/2014 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,3+ Family Apt. Building,11215,NaN,NaN,BROOKLYN,Closed,07/16/2014 02:30:53 PM,07/01/2014 12:00:00 AM,06 BROOKLYN,BROOKLYN,40.662800,-73.978348
4,28272230,06/16/2014 12:00:00 AM,04/28/2014 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,Commercial Building,10002,174 ORCHARD STREET,ORCHARD STREET,NEW YORK,Pending,07/16/2014 11:05:03 PM,04/28/2014 12:00:00 AM,03 MANHATTAN,MANHATTAN,40.721688,-73.988391

In [7]:
demographics = pd.read_csv(r'data/Datathon Materials/demographics.csv')
demographics.head()

,year,geography,total_households,"$9,999_or_less","$10,000_to_$14,999","$15,000_to_$24,999","$25,000_to_$34,999","$35,000_to_$49,999","$50,000_to_$74,999","$75,000_to_$99,999",...,mean_soc_sec,mean_ret_income,mean_supp_sec_income,mean_cash_pub_income,food_stamp_benefits,population,pop_w_health_insurance,pop_w_private_health,pop_w_public_coverage,pop_no_health_insurance
0,2016,New York,7266187,556825,373344,691781,632230,832804,1177356,865492,...,18381,26534,9366,3825,1118434,19453583.0,17785491.0,12842299.0,7134416.0,1668092.0
1,2016,"Albany County, New York",124108,7606,6285,11507,10845,14900,22510,16017,...,19131,29496,9341,3743,14305,304048.0,287725.0,237720.0,93742.0,16323.0
2,2016,"Allegany County, New York",18032,1282,1193,2308,2110,3196,3521,2277,...,17561,19662,9160,3220,2872,47207.0,43052.0,32118.0,18423.0,4155.0
3,2016,"Bronx County, New York",490740,76719,45398,66942,54687,65338,74323,44111,...,14211,20862,8885,3598,179811,1414859.0,1240816.0,615421.0,754030.0,174043.0
4,2016,"Broome County, New York",78738,6134,4972,10079,8560,11189,14361,9432,...,18249,22972,9310,3492,12867,194413.0,183183.0,134119.0,78559.0,11230.0

In [8]:
demographics_city = pd.read_csv(r'data/Datathon Materials/demographics_city.csv')
demographics_city.head()

,nta_name,borough,nta_code,population,under_5_years,5-9_years,10-14_years,15-19_years,20-24_years,25-29_years,...,15000_to_24999,25000_to_34999,35000_to_49999,50000_to_74999,75000_to_99999,100000_to_149999,150000_to_199999,200000_or_more,median_income,mean_income
0,Allerton-Pelham Gardens,Bronx,BX31,28903,1679,1706,1763,2039,1964,1703,...,797,773,1160,1764,1155,1562,765,427,61638,78489
1,Annadale-Huguenot-Prince's Bay-Eltingville,Staten Island,SI01,27770,1397,1698,1817,1880,1720,1594,...,571,405,1008,1523,1346,2075,1086,1151,88288,109187
2,Arden Heights,Staten Island,SI48,25238,1507,1540,1596,1752,1614,1561,...,337,516,707,1421,1611,2021,1047,740,89570,101627
3,Astoria,Queens,QN70,78793,3480,3037,3060,3392,6630,11586,...,3673,2816,4725,6463,4557,4698,1627,1197,54882,70094
4,Auburndale,Queens,QN48,19996,917,966,1063,1168,1214,1307,...,445,632,690,1417,1060,1237,589,433,70772,84402

In [12]:
food_establishment_inspections = pd.read_csv(r'data/Datathon Materials/food_establishment_inspections.csv', engine='python')
food_establishment_inspections.head()

,facility,address,inspection_date,violation_item,violation_description,critical_violation,num_critical,num_critical_not_corrected,num_noncritical,local_health_department,...,permit_expiration_date,food_service_type,food_service_description,nys_inspection_id,inspection_type,inspection_comments,latitude,longitude,Unnamed: 23,Unnamed: 24
0,STEVIE V'S - LA ROSA PIZZERIA,"6318 ROBINSON ROAD, LOCKPORT",10/3/17,15A,"Floors, walls, ceilings, not smooth, properly ...",Not Critical Violation,0.0,0.0,3.0,Niagara County,...,10/31/18,Food Service Establishment,Restaurant/Catering Operation,286815,Inspection,Restrooms: OK\nFood Testing Thermometers: OK\n...,43.124090,-78.736710,NaN,NaN
1,SCOOPS-N-MORE,"90 GLENEIDA AVENUE, CARMEL",9/9/15,10B,Non-food contact surfaces and equipment are im...,Not Critical Violation,0.0,0.0,1.0,Putnam County,...,3/31/18,Food Service Establishment,Restaurant,299840,Inspection,NaN,41.429351,-73.679427,NaN,NaN
2,J & B LUNCHEONETTE,"189 ROUTE 9W, HAVERSTRAW",4/15/10,None,NaN,Not Critical Violation,0.0,0.0,0.0,Rockland County,...,4/30/18,Food Service Establishment,Food Service Establishment,303561,Inspection,NaN,41.198585,-73.981861,NaN,NaN
3,STOLTZFUS PASTRIES,"2325 McCULLOCH ROAD, ROMULUS",7/12/12,None,NaN,Not Critical Violation,0.0,0.0,0.0,Seneca County,...,7/30/18,Food Service Establishment,Bakery,308241,Inspection,NaN,42.786649,-76.809727,NaN,NaN
4,BOATYARD GRILL,"525 TAUGHANNOCK BOULEVARD, ITHACA",8/26/11,None,NaN,Not Critical Violation,0.0,0.0,0.0,Tompkins County,...,3/31/18,Food Service Establishment,Restaurant/Catering Operation,313774,Re-Inspection,NaN,42.442929,-76.513121,NaN,NaN

In [10]:
geographic = pd.read_csv(r'data/Datathon Materials/geographic.csv')
geographic.head()

,BK88,QN52,QN48,QN51,QN27,BX35,BX98,QN07,MN06,QN02,...,MN25,MN24,MN23,MN13,MN15,MN32,MN33,MN99,QN18,QN29
0,-73.976051,-73.794934,-73.775740,-73.803792,-73.861099,-73.896967,-73.872873,-73.757258,-73.946080,-73.760316,...,-74.000784,-73.992605,-73.989904,-74.001535,-73.993833,-73.938048,-73.935054,-74.010930,-73.858726,-73.867911
1,40.631284,40.757806,40.743334,40.775618,40.763673,40.834350,40.785983,40.718147,40.821271,40.675118,...,40.694295,40.724145,40.734443,40.762653,40.772940,40.780838,40.791695,40.684500,40.735717,40.744942
2,-73.977167,-73.794749,-73.775799,-73.800991,-73.859931,-73.896787,-73.872886,-73.755890,-73.946404,-73.758806,...,-74.000960,-73.992634,-73.989870,-74.001339,-73.993789,-73.937903,-73.935108,-74.011934,-73.858672,-73.867877
3,40.630755,40.755636,40.743326,40.775397,40.762209,40.834133,40.785971,40.716307,40.820580,40.673014,...,40.694077,40.724065,40.733535,40.762217,40.772912,40.780758,40.791658,40.683896,40.735627,40.744824
4,-73.977000,-73.794579,-73.778060,-73.798653,-73.859668,-73.896303,-73.872983,-73.754702,-73.946720,-73.758598,...,-74.003015,-73.993093,-73.990028,-74.001279,-73.993727,-73.937796,-73.935173,-74.012177,-73.858585,-73.867852

# analysis community_health

In [13]:
list(community_health)

['county_name',
 'health_topic',
 'indicator',
 'event_count',
 'avg_num_of_denominator',
 'unit_measurement',
 'precent_or_rate',
 'low_limit_95p_CI',
 'upp_limit_95p_CI',
 'data_comment',
 'year',
 'data_source',
 'lat_long']

In [15]:
community_health['health_topic'].unique()

array(['Family Planning/Natality Indicators', 'Cancer Indicators',
       'Oral Health Indicators', 'Maternal and Infant Health Indicators',
       'Injury Indicators',
       'Socio-Economic Status and General Health Indicators',
       'Cardiovascular Disease Indicators',
       'Child and Adolescent Health Indicators',
       'Obesity and Related Indicators', 'Cirrhosis/Diabetes Indicators',
       'HIV/AIDS and Other Sexually Transmitted Infection Indicators',
       'Respiratory Disease Indicators',
       'Tobacco, Alcohol and Other Substance Abuse Indicators',
       'Communicable Disease Indicators',
       'Occupational Health Indicators'], dtype=object)

In [16]:
community_health['indicator'].unique()

array(['Percentage of births within 24 months of previous pregnancy',
       'Cervix uteri cancer incidence rate per 100,000',
       'Pregnancy rate per 1,000 (all pregnancies/female population aged 15-44 years)',
       'Teen pregnancy rate per 1,000 females aged 10-14 years',
       'Teen pregnancy rate per 1,000 females aged 15-17 years',
       'Oral cancer mortality per 100,000 - Aged 45-74 years',
       'Teen pregnancy rate per 1,000 females aged 15-19 years',
       'Teen pregnancy rate per 1,000 females aged 18-19 years',
       'Abortion ratio (induced abortions per 1,000 live births) - Aged 15-19 years',
       'Abortion ratio (induced abortions per 1,000 live births) - All ages',
       'Percentage of births delivered by cesarean section',
       'Percentage of births to women aged 25 years and older without a high school education',
       'Percentage of births to out-of-wedlock mothers',
       'Percentage of births that were first births',
       'Mortality rate per 1,000 live births - Neonatal (<28 days)',
       'Percentage of births to teens - Aged 15-17 years',
       'Percentage of births that were multiple births',
       'Percentage of births with early (1st trimester) prenatal care',
       'Unintentional injury hospitalization rate per 10,000',
       'Percentage of births with late (3rd trimester) or no prenatal care',
       'Percentage of births with adequate prenatal care (Kotelchuck)',
       'Percentage of infants fed any breast milk in delivery hospital',
       'Percentage of infants fed exclusively breast milk in delivery hospital',
       'Birth rate per 1,000 population',
       'Mortality rate per 1,000 live births - Infant (<1 year)',
       'Mortality rate per 1,000 live births - Post-neonatal (1 month to 1 year)',
       'Percentage of births to teens - Aged 15-19 years',
       'Age-adjusted poisoning hospitalization rate per 10,000',
       'Percentage very low birthweight (<1.5kg) singleton births',
       'Mortality rate per 1,000 live births - Fetal death (20 weeks gestation or more)',
       'Mortality rate per 1,000 live births - Perinatal (20 weeks gestation - <28 days of life)',
       'Mortality rate per 1,000 live births - Perinatal (28 weeks gestation - <7 days of life)',
       'Maternal mortality rate per 100,000 live births',
       'Percentage very low birthweight (<1.5 kg) births',
       'Percentage low birthweight (<2.5 kg) births',
       'Percentage low birthweight (<2.5kg) singleton births',
       'Percentage of premature births with <32 weeks gestation',
       'Percentage of premature births with 32 - <37 weeks gestation',
       'Percentage of births to women aged 35 years and older',
       'Percentage of premature births with <37 weeks gestation',
       'Percentage of births with a 5 minute APGAR <6',
       'Fertility rate per 1,000 females - Aged 15-44 years',
       'Teen fertility rate per 1,000 (births to mothers aged 10-14 years/female population aged 10-14 years)',
       'Teen fertility rate per 1,000 (births to mothers aged 15-17 years/female population aged 15-17 years)',
       'Teen fertility rate per 1,000 (births to mothers aged 15-19 years/female population aged 15-19 years)',
       'Cardiovascular disease mortality rate per 100,000',
       'Teen fertility rate per 1,000 (births to mothers aged 18-19 years/female population aged 18-19 years)',
       'Congestive heart failure mortality rate per 100,000',
       'Age-adjusted congestive heart failure mortality rate per 100,000',
       'Congestive heart failure premature death (aged 35-64 years) rate per 100,000',
       'Congestive heart failure pretransport mortality rate per 100,000',
       'Childhood mortality rate per 100,000 - Aged 1-4 years',
       'Cerebrovascular disease (stroke) mortality rate per 100,000',
       'Age-adjusted cerebrovascular disease (stroke) mortality rate per 100,000',
       'Cerebrovascular disease (stroke) premature death (aged 35-64 years) rate per 100,000',
       'Cerebrovascular disease (stroke) pretransport mortality rate per 100,000',
       'Childhood mortality rate per 100,000 - Aged 10-14 years',
       'Childhood mortality rate per 100,000 - Aged 5-9 years',
       'Childhood mortality rate per 100,000 - Aged 5-14 years',
       'Cirrhosis mortality rate per 100,000',
       'Age-adjusted cardiovascular disease mortality rate per 100,000',
       'Diabetes mortality rate per 100,000',
       'Cardiovascular disease premature death (aged 35-64 years) rate per 100,000',
       'Suicide mortality rate per 100,000 - Aged 15-19 years',
       'Childhood mortality rate per 100,000 - Aged 15-19 years',
       'Age-adjusted cirrhosis mortality rate per 100,000',
       'Age-adjusted diabetes mortality rate per 100,000',
       'Unintentional injury mortality rate per 100,000',
       'AIDS mortality rate per 100,000',
       'Age-adjusted AIDS mortality rate per 100,000',
       'Suicide mortality rate per 100,000',
       'Age-adjusted suicide mortality rate per 100,000',
       'Motor vehicle mortality rate per 100,000',
       'Homicide mortality rate per 100,000',
       'Age-adjusted homicide mortality rate per 100,000',
       'Age-adjusted unintentional injury mortality rate per 100,000',
       'Age-adjusted motor vehicle mortality rate per 100,000',
       'Non-motor vehicle mortality rate per 100,000',
       'Age-adjusted non-motor vehicle mortality rate per 100,000',
       'Cardiovascular disease pretransport mortality rate per 100,000',
       'Chronic lower respiratory disease mortality rate per 100,000',
       'Age-adjusted chronic lower respiratory disease mortality rate per 100,000',
       'Asthma mortality rate per 100,000',
       'Age-adjusted asthma mortality rate per 100,000',
       'Total mortality rate per 100,000',
       'Age-adjusted total mortality rate per 100,000',
       'Percentage premature deaths (aged less than 75 years)',
       'Years of potential life lost per 100,000',
       'Heart attack mortality rate per 100,000',
       'Age-adjusted heart attack mortality rate per 100,000',
       'Disease of the heart mortality rate per 100,000',
       'Age-adjusted disease of the heart mortality rate per 100,000',
       'Disease of the heart pretransport mortality rate per 100,000',
       'Disease of the heart premature death (aged 35-64 years) mortality rate per 100,000',
       'Coronary heart disease mortality rate per 100,000',
       'Age-adjusted coronary heart disease mortality rate per 100,000',
       'Coronary heart disease premature death (aged 35-64 years) rate per 100,000',
       'Coronary heart disease pretransport mortality rate per 100,000',
       'Caries outpatient visit rate per 10,000 - Aged 3-5 years',
       'Total emergency department visit rate per 10,000',
       'Age-adjusted total emergency department visit rate per 10,000',
       'Chronic kidney disease emergency department visit rate per 10,000 (any diagnosis)',
       'Age-adjusted chronic kidney disease emergency department visit rate per 10,000 (any diagnosis)',
       'All cancer incidence rate per 100,000',
       'Hypertension emergency department visit rate per 10,000 (any diagnosis) - Aged 18 years and older',
       'Hypertension emergency department visit rate per 10,000 - Aged 18 years and older',
       'Female breast cancer mortality rate per 100,000',
       'Median household income in US dollars',
       'Percentage of children aged <19 years with health insurance',
       'Percentage of adults aged 18-64 years with health insurance',
       'Percentage of high school drop out',
       'Age-adjusted percentage of adults who did not receive medical care because of cost',
       'Alcohol related motor vehicle injuries and deaths per 100,000',
       'Age-adjusted percentage of adults with regular health care provider',
       'Age-adjusted percentage of adults who had poor mental health 14 or more days within the past month',
       'Age-adjusted percentage of adults who smoke cigarettes',
       'Age-adjusted percentage of adults living in homes where smoking is prohibited',
       'Age-adjusted female breast cancer mortality rate per 100,000',
       'Female breast cancer late stage incidence rate per 100,000',
       'Age-adjusted percentage of adults who binge drink',
       'Cervix uteri cancer mortality rate per 100,000',
       'Age-adjusted female breast cancer late stage incidence rate per 100,000',
       'Percentage of children born in 2011 with a lead screening - aged 18-35 months',
       'Percentage of children with recommended number of well child visits in government sponsored insurance programs',
       'Percentage of children aged 0-15 months with recommended number of well child visits in government sponsored insurance programs',
       'Percentage of children aged 3-6 years with recommended number of well child visits in government sponsored insurance programs',
       'Percentage of children aged 12-21 years with recommended number of well child visits in government sponsored insurance programs',
       'Percentage of children, aged 2-21 years, with at least one dental visit in government sponsored insurance programs',
       'Percentage of women, aged 50-74 years, who had a mammogram between October 1, 2012 and December 31, 2014',
       'Percentage of sexually active young women aged 16-24 with at least one Chlamydia test in Medicaid program',
       'Percentage of Medicaid enrollees (aged 2-20 years) with at least one preventive dental visit within the last year',
       'Age-adjusted cervix uteri cancer incidence rate per 100,000',
       'Age-adjusted cervix uteri cancer mortality rate per 100,000',
       'Ovarian cancer incidence rate per 100,000',
       'Prostate cancer mortality rate per 100,000',
       'Age-adjusted ovarian cancer incidence rate per 100,000',
       'All cancers mortality rate per 100,000',
       'Ovarian cancer mortality rate per 100,000',
       'Age-adjusted ovarian cancer mortality rate per 100,000',
       'Prostate cancer incidence rate per 100,000',
       'Age-adjusted prostate cancer incidence rate per 100,000',
       'Age-adjusted prostate cancer mortality rate per 100,000',
       'Prostate cancer late stage incidence rate per 100,000',
       'Age-adjusted prostate cancer late stage incidence rate per 100,000',
       'Melanoma cancer mortality rate per 100,000',
       'Age-adjusted melanoma cancer mortality rate per 100,000',
       'Age-adjusted all cancer incidence rate per 100,000',
       'Age-adjusted percentage of women 18 years and older with Pap smear in past 3 years',
       'Age-adjusted all cancers mortality rate per 100,000',
       'Percentage of women 40 years and older with mammography screening in past 2 years',
       'Age-adjusted percentage of adults with physician diagnosed angina, heart attack or stroke',
       'Age-adjusted percentage of adults ever had blood cholesterol checked',
       'Percentage of children born in 2011 with a lead screening aged 0-8 months',
       'Lip, oral cavity and pharynx cancer incidence rate per 100,000',
       'Age-adjusted percentage of adults ever told they have high blood pressure',
       'Percentage of children born in 2011 with a lead screening - aged 9-17 months',
       'Percentage of children born in 2011 with at least two lead screenings by 36 months',
       'Incidence of confirmed high blood lead level (10 micrograms or higher per deciliter) - rate per 1,000 tested children aged <72 months',
       'Age-adjusted percentage of adults with physician diagnosed diabetes',
       'Pertussis incidence per 100,000', 'Mumps incidence per 100,000',
       'H. influenza incidence per 100,000',
       'Meningococcal incidence per 100,000',
       'Hepatitis A incidence per 100,000',
       'Acute hepatitis B incidence per 100,000',
       'Tuberculosis incidence per 100,000',
       'Age-adjusted lip, oral cavity and pharynx cancer incidence rate per 100,000',
       'E. coli O157 incidence per 100,000',
       'Salmonella incidence per 100,000',
       'Shigella incidence per 100,000',
       'Lip, oral cavity and pharynx cancer mortality rate per 100,000',
       'Lyme disease incidence per 100,000',
       'Percentage of adults 65 years and older had a flu shot or flu vaccine (mist) in last year',
       'HIV case rate per 100,000',
       'Percentage of adults aged 65 years and older who ever received pneumonia shot',
       'Colon and rectum cancer incidence rate per 100,000',
       'Age-adjusted HIV case rate per 100,000',
       'AIDS case rate per 100,000',
       'Age-adjusted AIDS case rate per 100,000',
       'Early syphilis case rate per 100,000',
       'Gonorrhea case rate per 100,000 - All ages',
       'Gonorrhea case rate per 100,000 - Aged 15-19 years',
       'Chlamydia case rate per 100,000 males - All ages',
       'Chlamydia case rate per 100,000 males - Aged 15-19 years',
       'Age-adjusted lip, oral cavity and pharynx cancer mortality rate per 100,000',
       'Chlamydia case rate per 100,000 males - Aged 20-24 years',
       'Chlamydia case rate per 100,000 females - All ages',
       'Chlamydia case rate per 100,000 females - Aged 15-19 years',
       'Chlamydia case rate per 100,000 females - Aged 20-24 years',
       'Age-adjusted colon and rectum cancer incidence rate per 100,000',
       'Colon and rectum cancer mortality rate per 100,000',
       'Percentage of pregnant women in WIC with early (1st trimester) prenatal care',
       'Percentage of pregnant women in WIC who were pre-pregnancy underweight (BMI less than 18.5)',
       'Percentage of pregnant women in WIC who were pre-pregnancy overweight but not obese (BMI 25 to less than 30)',
       'Percentage of pregnant women in WIC who were pre-pregnancy obese (BMI 30 or higher)',
       'Percentage of pregnant women in WIC with anemia in 3rd trimester',
       'Percentage of pregnant women in WIC with gestational weight gain greater than ideal',
       'Percentage of pregnant women in WIC with gestational diabetes',
       'Lung and bronchus cancer incidence rate per 100,000',
       'Percentage of pregnant women in WIC with hypertension during pregnancy',
       'Percentage of WIC infants breastfeeding at least 6 months',
       'Percentage overweight but not obese (85th-<95th percentile) - Students (with weight status information in SWSCRS) in elementary, middle and high school',
       'Age-adjusted colon and rectum cancer mortality rate per 100,000',
       'Percentage obese (95th percentile or higher) - Students (with weight status information in SWSCRS) in elementary, middle and high school',
       'Percentage overweight or obese (85th percentile or higher) - Students (with weight status information in SWSCRS) in elementary, middle and high school',
       'Percentage obese (95th percentile or higher ) - Students (with weight status information in SWSCRS) in elementary school',
       'Percentage overweight but not obese (85th-<95th percentile) - Students (with weight status information in SWSCRS) in elementary school',
       'Percentage overweight or obese (85th percentile or higher) - Students (with weight status information in SWSCRS) in elementary school',
       'Percentage overweight but not obese (85th-<95th percentile) - Students (with weight status information in SWSCRS) in middle and high school',
       'Percentage obese (95th percentile or higher ) - Students (with weight status information in SWSCRS) in middle and high school',
       'Percentage obese (95th percentile or higher) children (aged 2-4 years) in WIC',
       'Percentage overweight or obese (85th percentile or higher) - Students (with weight status information in SWSCRS) in middle and high school',
       'Age-adjusted lung and bronchus cancer incidence rate per 100,000',
       'Percentage of children (aged 2-4 years) enrolled in WIC watching TV 2 hours or less per day',
       'Age-adjusted percentage of adults overweight or obese (BMI 25 or higher)',
       'Incidence of malignant mesothelioma per 100,000 persons aged 15 years and older',
       'Age-adjusted percentage of adults obese (BMI 30 or higher)',
       'Age-adjusted percentage of adults who did not participate in leisure time physical activity in last 30 days',
       'Age-adjusted percentage of adults eating 5 or more fruits or vegetables per day',
       'Pneumoconiosis hospitalization rate per 100,000 - Aged 15 years and older',
       'Lung and bronchus cancer mortality rate per 100,000',
       'Asbestosis hospitalization rate per 100,000 - Aged 15 years and older',
       'Work-related hospitalizations per 100,000 employed persons aged 16 years and older',
       'Elevated blood lead levels (greater than or equal to 10 micrograms per deciliter) per 100,000 employed persons aged 16 years and older',
       'Fatal work-related injuries per 100,000 employed persons aged 16 years and older',
       'Age-adjusted lung and bronchus cancer mortality rate per 100,000',
       'Percentage of 3rd grade children with caries experience',
       'Percentage of 3rd grade children with untreated caries',
       'Percentage of 3rd grade children with dental sealants',
       'Percentage of 3rd grade children with dental insurance',
       'Percentage of 3rd grade children with at least one dental visit in last year',
       'Percentage of 3rd grade children reported taking fluoride tablets regularly',
       'Female breast cancer incidence rate per 100,000',
       'Age-adjusted percentage of adults who had a dentist visit within the past year',
       'Percentage of Medicaid enrollees with at least one dental visit within the last year',
       'Percentage of Medicaid enrollees with at least one preventive dental visit within the last year',
       'Diabetes hospitalization rate per 10,000 (primary diagnosis)',
       'Percentage of Medicaid enrollees (aged 2-20 years) who had at least one dental visit within the last year',
       'Age-adjusted diabetes hospitalization rate per 10,000 (primary diagnosis)',
       'Age-adjusted percentage of adults with current asthma',
       'Total population', 'Percentage of labor force unemployed',
       'Percentage of population below poverty',
       'Percentage of children aged <18 years below poverty',
       'Age-adjusted female breast cancer incidence rate per 100,000',
       'Cardiovascular disease hospitalization rate per 10,000',
       'Pneumonia/flu hospitalization rate (Aged 65 years and older) per 10,000',
       'Cirrhosis hospitalization rate per 10,000',
       'Age-adjusted cirrhosis hospitalization rate per 10,000',
       'Diabetes hospitalization rate per 10,000 (any diagnosis)',
       'Age-adjusted diabetes hospitalization rate per 10,000 (any diagnosis)',
       'Pelvic inflammatory disease (PID) hospitalization rate per 10,000 females - Aged 15-44 years',
       'Self-inflicted injury hospitalization rate per 10,000',
       'Age-adjusted self-inflicted injury hospitalization rate per 10,000',
       'Assault hospitalization rate per 10,000',
       'Self-inflicted injury hospitalization rate per 10,000 -  Aged 15-19 years',
       'Age-adjusted assault hospitalization rate per 10,000',
       'Age-adjusted unintentional injury hospitalization rate per 10,000',
       'Unintentional injury hospitalization rate per 10,000 - Aged <10 years',
       'Age-adjusted cardiovascular disease hospitalization rate per 10,000',
       'Disease of the heart hospitalization rate per 10,000',
       'Unintentional injury hospitalization rate per 10,000 - Aged 10-14 years',
       'Unintentional injury hospitalization rate per 10,000 - Aged 15-24 years',
       'Falls hospitalization rate per 10,000 - Aged 15-24 years',
       'Unintentional injury hospitalization rate per 10,000 - Aged 25-64 years',
       'Unintentional injury hospitalization rate per 10,000 - Aged 65 years and older',

In [17]:
community_health.groupby('health_topic')['indicator'].unique()

health_topic
Cancer Indicators                                               [Cervix uteri cancer incidence rate per 100,00...
Cardiovascular Disease Indicators                               [Cardiovascular disease mortality rate per 100...
Child and Adolescent Health Indicators                          [Childhood mortality rate per 100,000 - Aged 1...
Cirrhosis/Diabetes Indicators                                   [Cirrhosis mortality rate per 100,000, Diabete...
Communicable Disease Indicators                                 [Pertussis incidence per 100,000, Mumps incide...
Family Planning/Natality Indicators                             [Percentage of births within 24 months of prev...
HIV/AIDS and Other Sexually Transmitted Infection Indicators    [AIDS mortality rate per 100,000, Age-adjusted...
Injury Indicators                                               [Unintentional injury hospitalization rate per...
Maternal and Infant Health Indicators                           [Percentage of births delivered by cesarean se...
Obesity and Related Indicators                                  [Age-adjusted cerebrovascular disease (stroke)...
Occupational Health Indicators                                  [Incidence of malignant mesothelioma per 100,0...
Oral Health Indicators                                          [Oral cancer mortality per 100,000 - Aged 45-7...
Respiratory Disease Indicators                                  [Chronic lower respiratory disease mortality r...
Socio-Economic Status and General Health Indicators             [Birth rate per 1,000 population, Total mortal...
Tobacco, Alcohol and Other Substance Abuse Indicators           [Alcohol related motor vehicle injuries and de...
Name: indicator, dtype: object

In [31]:
community_health_summary = pd.DataFrame(community_health.groupby(['health_topic','indicator']).size())
community_health_summary

                                                                                                        0
health_topic                                       indicator
Cancer Indicators                                  Age-adjusted all cancer incidence rate per 100,000  74
                                                   Age-adjusted all cancers mortality rate per 100...  74
                                                   Age-adjusted cervix uteri cancer incidence rate...  74
                                                   Age-adjusted cervix uteri cancer mortality rate...  74
                                                   Age-adjusted colon and rectum cancer incidence ...  74
                                                   Age-adjusted colon and rectum cancer mortality ...  74
                                                   Age-adjusted female breast cancer incidence rat...  74
                                                   Age-adjusted female breast cancer late stage in...  74
                                                   Age-adjusted female breast cancer mortality rat...  74
                                                   Age-adjusted lip, oral cavity and pharynx cance...  74
                                                   Age-adjusted lip, oral cavity and pharynx cance...  74
                                                   Age-adjusted lung and bronchus cancer incidence...  74
                                                   Age-adjusted lung and bronchus cancer mortality...  74
                                                   Age-adjusted melanoma cancer mortality rate per...  74
                                                   Age-adjusted ovarian cancer incidence rate per ...  74
                                                   Age-adjusted ovarian cancer mortality rate per ...  74
                                                   Age-adjusted percentage of women 18 years and o...  69
                                                   Age-adjusted prostate cancer incidence rate per...  74
                                                   Age-adjusted prostate cancer late stage inciden...  74
                                                   Age-adjusted prostate cancer mortality rate per...  74
                                                   All cancer incidence rate per 100,000               74
                                                   All cancers mortality rate per 100,000              74
                                                   Cervix uteri cancer incidence rate per 100,000      74
                                                   Cervix uteri cancer mortality rate per 100,000      74
                                                   Colon and rectum cancer incidence rate per 100,000  74
                                                   Colon and rectum cancer mortality rate per 100,000  74
                                                   Female breast cancer incidence rate per 100,000     74
                                                   Female breast cancer late stage incidence rate ...  74
                                                   Female breast cancer mortality rate per 100,000     74
                                                   Lip, oral cavity and pharynx cancer incidence r...  74
                                                   Lip, oral cavity and pharynx cancer mortality r...  74
                                                   Lung and bronchus cancer incidence rate per 100...  74
                                                   Lung and bronchus cancer mortality rate per 100...  74
                                                   Melanoma cancer mortality rate per 100,000          74
                                                   Ovarian cancer incidence rate per 100,000           74
                                                   Ovarian cancer mortality rate per 100,000           74
                                                   Percentage of women 40 years and older with mam...  74
                                                   Percentage of women, aged 50-74 years, who had ...  74
                                                   Prostate cancer incidence rate per 100,000          74
                                                   Prostate cancer late stage incidence rate per 1...  74
                                                   Prostate cancer mortality rate per 100,000          74
Cardiovascular Disease Indicators                  Age-adjusted cardiovascular disease hospitaliza...  74
                                                   Age-adjusted cardiovascular disease mortality r...  74
                                                   Age-adjusted cerebrovascular disease (stroke) h...  74
                                                   Age-adjusted cerebrovascular disease (stroke) m...  74
                                                   Age-adjusted chronic kidney disease emergency d...  74
                                                   Age-adjusted chronic kidney disease hospitaliza...  74
                                                   Age-adjusted congestive heart failure hospitali...  74
                                                   Age-adjusted congestive heart failure mortality...  74
                                                   Age-adjusted coronary heart disease hospitaliza...  74
                                                   Age-adjusted coronary heart disease mortality r...  74
                                                   Age-adjusted disease of the heart hospitalizati...  74
                                                   Age-adjusted disease of the heart mortality rat...  74
                                                   Age-adjusted heart attack hospitalization rate ...  74
                                                   Age-adjusted heart attack mortality rate per 10...  74
                                                   Age-adjusted percentage of adults ever had bloo...  74
                                                   Age-adjusted percentage of adults ever told the...  74
                                                   Age-adjusted percentage of adults with physicia...  58
                                                   Cardiovascular disease hospitalization rate per...  74
                                                   Cardiovascular disease mortality rate per 100,000   74
                                                   Cardiovascular disease premature death (aged 35...  74
                                                   Cardiovascular disease pretransport mortality r...  74
                                                   Cerebrovascular disease (stroke) hospitalizatio...  74
                                                   Cerebrovascular disease (stroke) mortality rate...  74
                                                   Cerebrovascular disease (stroke) premature deat...  74
                                                   Cerebrovascular disease (stroke) pretransport m...  74
                                                   Chronic kidney disease emergency department vis...  74
                                                   Chronic kidney disease hospitalization rate per...  74
                                                   Congestive heart failure hospitalization rate p...  74
                                                   Congestive heart failure mortality rate per 100...  74
                                                   Congestive heart failure premature death (aged ...  74
                                                   Congestive heart failure pretransport mortality...  74
                                                   Coronary heart disease hospitalization rate per...  74
                                                   Coronary heart disease mortality rate per 100,000   74
                                                   Coronary heart disease premature death (aged 35...  74
                                                   Coronary heart disease pretransport mortality r...  74
                                                   Disease of the heart hospitalization rate per 1...  74
                                                   Disease of the heart mortality rate per 100,000     74
                                                   Disease of the heart premature death (aged 35-6...  74
                                                   Disease of the heart pretransport mortality rat...  74
                                                   Heart attack hospitalization rate per 10,000        74
                                                   Heart attack mortality rate per 100,000             74
                                                   Hypertension emergency department visit rate pe...  74
                                                   Hypertension emergency department visit rate pe...  74
                                                   Hypertension hospitalization rate per 10,000 (a...  74
                                                   Hypertension hospitalization rate per 10,000 - ...  74
Child and Adolescent Health Indicators             Asthma hospitalization rate per 10,000 - Aged 0...  74
                                                   Asthma hospitalization rate per 10,000 - Aged 0...  74
                                                   Asthma hospitalization rate per 10,000 - Aged 5...  74
                                                   Childhood mortality rate per 100,000 - Aged 1-4...  74
                                                   Childhood mortality rate per 100,000 - Aged 10-...  74
                                                   Childhood mortality rate per 100,000 - Aged 15-...  74
                                                   Childhood mortality rate per 100,000 - Aged 5-1...  74
                                                   Childhood mortality rate per 100,000 - Aged 5-9...  74
                                                   Gastroenteritis hospitalization rate per 10,000...  74
                                                   Incidence of confirmed high blood lead level (1...  74
                                                   Otitis media hospitalization rate per 10,000 - ...  74
                                                   Percentage of children aged 0-15 months with re...  74
                                                   Percentage of children aged 12-21 years with re...  74
                                                   Percentage of children aged 3-6 years with reco...  74
                                                   Percentage of children born in 2011 with a lead...  74
                                                   Percentage of children born in 2011 with a lead...  74
                                                   Percentage of children born in 2011 with a lead...  74
                                                   Percentage of children born in 2011 with at lea...  74
                                                   Percentage of children with recommended number ...  74
                                                   Pneumonia hospitalization rate per 10,000 - Age...  74
Cirrhosis/Diabetes Indicators                      Age-adjusted chronic kidney disease emergency d...  74
                                                   Age-adjusted chronic kidney disease hospitaliza...  74
                                                   Age-adjusted cirrhosis hospitalization rate per...  74
                                                   Age-adjusted cirrhosis mortality rate per 100,000   74
                                                   Age-adjusted diabetes hospitalization rate per ...  74
                                                   Age-adjusted diabetes hospitalization rate per ...  74
                                                   Age-adjusted diabetes mortality rate per 100,000    74
                                                   Age-adjusted percentage of adults with physicia...  74
                                                   Chronic kidney disease emergency department vis...  74
                                                   Chronic kidney disease hospitalization rate per...  74
                                                   Cirrhosis hospitalization rate per 10,000           74
                                                   Cirrhosis mortality rate per 100,000                74
                                                   Diabetes Short-term Complications hospitalizati...  74
                                                   Diabetes hospitalization rate per 10,000 (any d...  74
                                                   Diabetes hospitalization rate per 10,000 (prima...  74
                                                   Diabetes mortality rate per 100,000                 74
                                                   Diabetes short-term complications hospitalizati...  74
Communicable Disease Indicators                    Acute hepatitis B incidence per 100,000             74
                                                   E. coli O157 incidence per 100,000                  74
                                                   H. influenza incidence per 100,000                  74
                                                   Hepatitis A incidence per 100,000                   74
                                                   Lyme disease incidence per 100,000                  74
                                                   Meningococcal incidence per 100,000                 74
                                                   Mumps incidence per 100,000                         74
                                                   Percentage of adults 65 years and older had a f...  74
                                                   Percentage of adults aged 65 years and older wh...  74
                                                   Pertussis incidence per 100,000                     74
                                                   Pneumonia/flu hospitalization rate (Aged 65 yea...  74
                                                   Salmonella incidence per 100,000                    74
                                                   Shigella incidence per 100,000                      74
                                                   Tuberculosis incidence per 100,000                  74
Family Planning/Natality Indicators                Abortion ratio (induced abortions per 1,000 liv...  74
                                                   Abortion ratio (induced abortions per 1,000 liv...  74
                                                   Fertility rate per 1,000 females - Aged 15-44 y...  74
                                                   Percentage of births to teens - Aged 15-17 years    74
                                                   Percentage of births to teens - Aged 15-19 years    74
                                                   Percentage of births to women aged 35 years and...  74
                                                   Percentage of births within 24 months of previo...  74
                                                   Pregnancy rate per 1,000 (all pregnancies/femal...  74
                                                   Teen fertility rate per 1,000 (births to mother...  74
                                                   Teen fertility rate per 1,000 (births to mother...  74
                                                   Teen fertility rate per 1,000 (births to mother...  74
                                                   Teen fertility rate per 1,000 (births to mother...  74
                                                   Teen pregnancy rate per 1,000 females aged 10-1...  74
                                                   Teen pregnancy rate per 1,000 females aged 15-1...  74
                                                   Teen pregnancy rate per 1,000 females aged 15-1...  74
                                                   Teen pregnancy rate per 1,000 females aged 18-1...  74
HIV/AIDS and Other Sexually Transmitted Infecti... AIDS case rate per 100,000                          74
                                                   AIDS mortality rate per 100,000                     74
                                                   Age-adjusted AIDS case rate per 100,000             74
                                                   Age-adjusted AIDS mortality rate per 100,000        74
                                                   Age-adjusted HIV case rate per 100,000              74
                                                   Chlamydia case rate per 100,000 females - Aged ...  74
                                                   Chlamydia case rate per 100,000 females - Aged ...  74
                                                   Chlamydia case rate per 100,000 females - All ages  74
                                                   Chlamydia case rate per 100,000 males - Aged 15...  74
                                                   Chlamydia case rate per 100,000 males - Aged 20...  74
                                                   Chlamydia case rate per 100,000 males - All ages    74
                                                   Early syphilis case rate per 100,000                74
                                                   Gonorrhea case rate per 100,000 - Aged 15-19 years  74
                                                   Gonorrhea case rate per 100,000 - All ages          74
                                                   HIV case rate per 100,000                           74
                                                   Pelvic inflammatory disease (PID) hospitalizati...  74
                                                   Percentage of sexually active young women aged ...  74
Injury Indicators                                  Age-adjusted assault hospitalization rate per 1...  74
                                                   Age-adjusted falls hospitalization rate per 10,000  74
                                                   Age-adjusted homicide mortality rate per 100,000    74
                                                   Age-adjusted motor vehicle mortality rate per 1...  74
                                                   Age-adjusted non-motor vehicle mortality rate p...  74
                                                   Age-adjusted poisoning hospitalization rate per...  74
                                                   Age-adjusted self-inflicted injury hospitalizat...  74
                                                   Age-adjusted suicide mortality rate per 100,000     74
                                                   Age-adjusted traumatic brain injury hospitaliza...  74
                                                   Age-adjusted unintentional injury hospitalizati...  74
                                                   Age-adjusted unintentional injury mortality rat...  74
                                                   Alcohol related motor vehicle injuries and deat...  74
                                                   Assault hospitalization rate per 10,000             74
                                                   Falls hospitalization rate per 10,000               74
                                                   Falls hospitalization rate per 10,000 - Aged 10...  74
                                                   Falls hospitalization rate per 10,000 - Aged 15...  74
                                                   Falls hospitalization rate per 10,000 - Aged 25...  74

In [39]:
community_health_summary.loc[['Cardiovascular Disease Indicators','Child and Adolescent Health Indicators','Communicable Disease Indicators','Obesity and Related Indicators','Socio-Economic Status and General Health Indicators']]

                                                                                                        0
health_topic                                       indicator
Cardiovascular Disease Indicators                  Age-adjusted cardiovascular disease hospitaliza...  74
                                                   Age-adjusted cardiovascular disease mortality r...  74
                                                   Age-adjusted cerebrovascular disease (stroke) h...  74
                                                   Age-adjusted cerebrovascular disease (stroke) m...  74
                                                   Age-adjusted chronic kidney disease emergency d...  74
                                                   Age-adjusted chronic kidney disease hospitaliza...  74
                                                   Age-adjusted congestive heart failure hospitali...  74
                                                   Age-adjusted congestive heart failure mortality...  74
                                                   Age-adjusted coronary heart disease hospitaliza...  74
                                                   Age-adjusted coronary heart disease mortality r...  74
                                                   Age-adjusted disease of the heart hospitalizati...  74
                                                   Age-adjusted disease of the heart mortality rat...  74
                                                   Age-adjusted heart attack hospitalization rate ...  74
                                                   Age-adjusted heart attack mortality rate per 10...  74
                                                   Age-adjusted percentage of adults ever had bloo...  74
                                                   Age-adjusted percentage of adults ever told the...  74
                                                   Age-adjusted percentage of adults with physicia...  58
                                                   Cardiovascular disease hospitalization rate per...  74
                                                   Cardiovascular disease mortality rate per 100,000   74
                                                   Cardiovascular disease premature death (aged 35...  74
                                                   Cardiovascular disease pretransport mortality r...  74
                                                   Cerebrovascular disease (stroke) hospitalizatio...  74
                                                   Cerebrovascular disease (stroke) mortality rate...  74
                                                   Cerebrovascular disease (stroke) premature deat...  74
                                                   Cerebrovascular disease (stroke) pretransport m...  74
                                                   Chronic kidney disease emergency department vis...  74
                                                   Chronic kidney disease hospitalization rate per...  74
                                                   Congestive heart failure hospitalization rate p...  74
                                                   Congestive heart failure mortality rate per 100...  74
                                                   Congestive heart failure premature death (aged ...  74
                                                   Congestive heart failure pretransport mortality...  74
                                                   Coronary heart disease hospitalization rate per...  74
                                                   Coronary heart disease mortality rate per 100,000   74
                                                   Coronary heart disease premature death (aged 35...  74
                                                   Coronary heart disease pretransport mortality r...  74
                                                   Disease of the heart hospitalization rate per 1...  74
                                                   Disease of the heart mortality rate per 100,000     74
                                                   Disease of the heart premature death (aged 35-6...  74
                                                   Disease of the heart pretransport mortality rat...  74
                                                   Heart attack hospitalization rate per 10,000        74
                                                   Heart attack mortality rate per 100,000             74
                                                   Hypertension emergency department visit rate pe...  74
                                                   Hypertension emergency department visit rate pe...  74
                                                   Hypertension hospitalization rate per 10,000 (a...  74
                                                   Hypertension hospitalization rate per 10,000 - ...  74
Child and Adolescent Health Indicators             Asthma hospitalization rate per 10,000 - Aged 0...  74
                                                   Asthma hospitalization rate per 10,000 - Aged 0...  74
                                                   Asthma hospitalization rate per 10,000 - Aged 5...  74
                                                   Childhood mortality rate per 100,000 - Aged 1-4...  74
                                                   Childhood mortality rate per 100,000 - Aged 10-...  74
                                                   Childhood mortality rate per 100,000 - Aged 15-...  74
                                                   Childhood mortality rate per 100,000 - Aged 5-1...  74
                                                   Childhood mortality rate per 100,000 - Aged 5-9...  74
                                                   Gastroenteritis hospitalization rate per 10,000...  74
                                                   Incidence of confirmed high blood lead level (1...  74
                                                   Otitis media hospitalization rate per 10,000 - ...  74
                                                   Percentage of children aged 0-15 months with re...  74
                                                   Percentage of children aged 12-21 years with re...  74
                                                   Percentage of children aged 3-6 years with reco...  74
                                                   Percentage of children born in 2011 with a lead...  74
                                                   Percentage of children born in 2011 with a lead...  74
                                                   Percentage of children born in 2011 with a lead...  74
                                                   Percentage of children born in 2011 with at lea...  74
                                                   Percentage of children with recommended number ...  74
                                                   Pneumonia hospitalization rate per 10,000 - Age...  74
Communicable Disease Indicators                    Acute hepatitis B incidence per 100,000             74
                                                   E. coli O157 incidence per 100,000                  74
                                                   H. influenza incidence per 100,000                  74
                                                   Hepatitis A incidence per 100,000                   74
                                                   Lyme disease incidence per 100,000                  74
                                                   Meningococcal incidence per 100,000                 74
                                                   Mumps incidence per 100,000                         74
                                                   Percentage of adults 65 years and older had a f...  74
                                                   Percentage of adults aged 65 years and older wh...  74
                                                   Pertussis incidence per 100,000                     74
                                                   Pneumonia/flu hospitalization rate (Aged 65 yea...  74
                                                   Salmonella incidence per 100,000                    74
                                                   Shigella incidence per 100,000                      74
                                                   Tuberculosis incidence per 100,000                  74
Obesity and Related Indicators                     Age-adjusted cardiovascular disease hospitaliza...  74
                                                   Age-adjusted cardiovascular disease mortality r...  74
                                                   Age-adjusted cerebrovascular disease (stroke) h...  74
                                                   Age-adjusted cerebrovascular disease (stroke) m...  74
                                                   Age-adjusted diabetes hospitalization rate per ...  74
                                                   Age-adjusted diabetes mortality rate per 100,000    74
                                                   Age-adjusted percentage of adults eating 5 or m...  63
                                                   Age-adjusted percentage of adults obese (BMI 30...  74
                                                   Age-adjusted percentage of adults overweight or...  74
                                                   Age-adjusted percentage of adults who did not p...  74
                                                   Age-adjusted percentage of adults with physicia...  58
                                                   Age-adjusted percentage of adults with physicia...  74
                                                   Percentage obese (95th percentile or higher ) -...  68
                                                   Percentage obese (95th percentile or higher ) -...  68
                                                   Percentage obese (95th percentile or higher) - ...  68
                                                   Percentage obese (95th percentile or higher) ch...  74
                                                   Percentage of WIC infants breastfeeding at leas...  74
                                                   Percentage of children (aged 2-4 years) enrolle...  74
                                                   Percentage of pregnant women in WIC who were pr...  74
                                                   Percentage of pregnant women in WIC who were pr...  74
                                                   Percentage overweight but not obese (85th-<95th...  68
                                                   Percentage overweight but not obese (85th-<95th...  68
                                                   Percentage overweight but not obese (85th-<95th...  68
                                                   Percentage overweight or obese (85th percentile...  68
                                                   Percentage overweight or obese (85th percentile...  68
                                                   Percentage overweight or obese (85th percentile...  68
Socio-Economic Status and General Health Indica... Age-adjusted percentage of adults who did not r...  74
                                                   Age-adjusted percentage of adults who had poor ...  74
                                                   Age-adjusted percentage of adults with regular ...  74
                                                   Age-adjusted total emergency department visit r...  74
                                                   Age-adjusted total hospitalization rate per 10,000  74
                                                   Age-adjusted total mortality rate per 100,000       74
                                                   Birth rate per 1,000 population                     74
                                                   Median household income in US dollars               63
                                                   Percentage of adults aged 18-64 years with heal...  63
                                                   Percentage of children aged <18 years below pov...  63
                                                   Percentage of children aged <19 years with heal...  63
                                                   Percentage of high school drop out                  74
                                                   Percentage of labor force unemployed                74
                                                   Percentage of population below poverty              63
                                                   Percentage premature deaths (aged less than 75 ...  74
                                                   Total emergency department visit rate per 10,000    74
                                                   Total hospitalization rate per 10,000               74
                                                   Total mortality rate per 100,000                    74
                                                   Total population                                    74
                                                   Years of potential life lost per 100,000            74

Cardiovascular Disease Indicators (Maybe useful)

Child and Adolescent Health Indicators: Childhood mortality rate per 100,000 - Aged ... years; Gastroenteritis hospitalization rate per 10,000 - Aged 0-4 years

Communicable Disease Indicators: Salmonella incidence per 100,000; E. coli O157 incidence per 100,000

Obesity and Related Indicators:

Socio-Economic Status and General Health Indicators

________________

Food poisonning: Salmonella, Shigella, E. coli O157 incidence per 100,000

# Analysis food_establishment_inspections

In [40]:
list(food_establishment_inspections)

['facility',
 'address',
 'inspection_date',
 'violation_item',
 'violation_description',
 'critical_violation',
 'num_critical',
 'num_critical_not_corrected',
 'num_noncritical',
 'local_health_department',
 'county',
 'facility_code',
 'city',
 'zipcode',
 'municipality',
 'permit_expiration_date',
 'food_service_type',
 'food_service_description',
 'nys_inspection_id',
 'inspection_type',
 'inspection_comments',
 'latitude',
 'longitude',
 'Unnamed: 23',
 'Unnamed: 24']

In [46]:
pd.DataFrame(food_establishment_inspections.groupby('violation_description').size()).sort_values(by=0,ascending=True)

                                                        0
violation_description
Floors, walls, ceilings and fixtures attached t...      1
Food Quantity/Quality Sufficient  {7-2.19(b)}           1
Pool Safety Plan Developed/Implemented/Updated ...      1
Lighting and ventilation inadequate; improper [...      1
Insect, Rodent, Bat and Weed Control  {7-2.21, ...      1
Inadequate refrigeration or heated food storage...      1
Illnesses/Injuries reported within 24 hours  {7...      1
Surface drainage                                        1
App.5-D.3(b)  Well casing in good condition and...      1
Food contact surfaces not clean and sanitized o...      1
Food workers with inadequate personal cleanline...      1
Food not properly labeled; served; not listed o...      1
Food handling excessive [14-4.90]                       2
Wiping cloths improperly used [14-4.115]                2
Hand washing facilities inadequate [14-2.8, 14-...      2
Toxic items improperly stored or used [14-4.20(...      2
Personnel with unclean hands or clothing, tobac...      2
Food on display not protected from contaminatio...      2
Handwashing facilities - inadequate, unkempt, n...      2
Non-food contact surfaces not clean [14-4.110(c)]       2
Equipment not in good repair or maintained, not...      2
Valid permit to operate, conspicuously posted {...      3
Insects and rodents not controlled [14-4.160]           3
Dishwashing facilities and/or procedure not acc...      3
Thermometers inaccurate, improperly used, impro...      3
Potentially hazardous food held for an improper...      4
Whole frozen poultry or poultry breasts, other ...     13
All pork or any food containing pork is not hea...     27
All shell eggs or foods containing shell eggs a...     31
Unpasteurized milk and milk products used              68
Food workers prepare foods when ill with a dise...     81
All ground meat and foods containing ground mea...     81
Meat and meat products not from approved plants.       87
Acid foods are stored in containers or pipes th...     98
Commercially processed precooked potentially ha...    125
Unwrapped/potentially hazardous foods are reser...    127
Other potentially hazardous foods requiring coo...    161
Raw foods not properly washing prior to serving       166
Inadequate personal cleanliness                       328
All poultry, poultry stuffings, stuffed meats a...    400
Prepared food products contact equipment or wor...    432
Foods or food area/public area contamination by...    483
Cracked/dirty fresh eggs, liquid or frozen eggs...    521
Home canned goods, or canned goods from unappro...    538
Food workers prepare raw and cooked or ready to...    539
Food workers do not wash hands thoroughly after...    587
Improperly functioning on-site sewage disposal ...    722
Potentially hazardous foods such as salads prep...    740
Improper storage of cleaning equipment, linens,...    973
Shellfish not from approved sources, improperly...    982
Dressing rooms dirty, not provided, improperly ...   1073
Precooked, refrigerated potentially hazardous f...   1327
Enough hot holding equipment is not present, pr...   1519
Water/ice: unsafe, unapproved sources, cross co...   2863
Hair is improperly restrained                        4080
Adequate, leakproof, non-absorbent, vermin-proo...   4560
Canned foods found in poor conditions (leakers,...   4591
Tobacco is used; eating, drinking in food prepa...   4867
Food from unapproved source, spoiled, adulterat...   5065
Food workers do not use proper utensils to elim...   5551
Garbage storage areas not properly constructed ...   6237
Pesticide application not supervised by a certi...   6653
Improper thawing procedures used                     6874
Hot, cold running water not provided, pressure ...   7329
Potentially hazardous foods are not cooled by a...   7368
Enough refrigerated storage equipment is not pr...   7509
Accurate thermometers not available or used to ...   7974
Premises littered, unnecessary equipment and ar...   8255
Potentially hazardous foods are not kept at or ...  10305
Potentially hazardous foods are not stored unde...  10493
Improper use and storage of clean, sanitized eq...  11713
Single service items reused, improperly stored,...  13954
Cooked or prepared foods are subject to cross-c...  13981
Toxic chemicals are improperly labeled, stored ...  15068
Potentially hazardous foods are not kept at or ...  15159
In use food dispensing utensils improperly stored   16938
Effective measures not used to control entrance...  17396
Manual facilities inadequate, technique incorre...  20716
Insects, rodents present                            21336
Toilet facilities inadequate, inconvenient, dir...  22223
Miscellaneous, Economic Violation, Choking Post...  22650
Food (ice) contact surfaces are improperly desi...  24501
Wiping cloths dirty, not stored properly in san...  25880
Plumbing and sinks not properly sized, installe...  29248
Food contact surfaces not washed, rinsed and sa...  32509
Accurate thermometers not available or used to ...  36802
Handwashing facilities inaccessible, improperly...  39293
Non-food contact surfaces and equipment are imp...  57598
Lighting and ventilation inadequate, fixtures n...  63155
Non food contact surfaces of equipment not clean    66039
Food not protected during storage, preparation,...  79088
Floors, walls, ceilings, not smooth, properly c...  91362

In [47]:
pd.DataFrame(food_establishment_inspections.groupby('violation_description')[['num_critical','num_noncritical']].sum()).sort_values(by='num_critical',ascending=True)

                                                    num_critical  num_noncritical
violation_description
Wiping cloths improperly used [14-4.115]                     0.0              4.0
Floors, walls, ceilings and fixtures attached t...           0.0              1.0
Equipment not in good repair or maintained, not...           0.0              2.0
Thermometers inaccurate, improperly used, impro...           0.0              5.0
Surface drainage                                             0.0              2.0
Dishwashing facilities and/or procedure not acc...           0.0              6.0
Food workers with inadequate personal cleanline...           0.0              1.0
Valid permit to operate, conspicuously posted {...           0.0              8.0
Food contact surfaces not clean and sanitized o...           0.0              2.0
Hand washing facilities inadequate [14-2.8, 14-...           0.0              2.0
App.5-D.3(b)  Well casing in good condition and...           0.0              1.0
Illnesses/Injuries reported within 24 hours  {7...           0.0              2.0
Inadequate refrigeration or heated food storage...           0.0              2.0
Insect, Rodent, Bat and Weed Control  {7-2.21, ...           0.0              1.0
Insects and rodents not controlled [14-4.160]                0.0              4.0
Pool Safety Plan Developed/Implemented/Updated ...           0.0              1.0
Lighting and ventilation inadequate; improper [...           0.0              2.0
Food Quantity/Quality Sufficient  {7-2.19(b)}                0.0              1.0
Food not properly labeled; served; not listed o...           1.0              3.0
Food handling excessive [14-4.90]                            1.0              3.0
Personnel with unclean hands or clothing, tobac...           1.0              4.0
Handwashing facilities - inadequate, unkempt, n...           1.0              4.0
Food on display not protected from contaminatio...           1.0              4.0
Non-food contact surfaces not clean [14-4.110(c)]            1.0              3.0
Toxic items improperly stored or used [14-4.20(...           2.0              3.0
Potentially hazardous food held for an improper...           4.0              4.0
Whole frozen poultry or poultry breasts, other ...          27.0             68.0
All shell eggs or foods containing shell eggs a...          92.0            223.0
All pork or any food containing pork is not hea...          95.0            111.0
Unpasteurized milk and milk products used                  150.0            357.0
Meat and meat products not from approved plants.           177.0            419.0
Raw foods not properly washing prior to serving            187.0           1155.0
Food workers prepare foods when ill with a dise...         205.0            581.0
All ground meat and foods containing ground mea...         210.0            395.0
Acid foods are stored in containers or pipes th...         240.0            628.0
Commercially processed precooked potentially ha...         282.0            566.0
Unwrapped/potentially hazardous foods are reser...         349.0            886.0
Inadequate personal cleanliness                            391.0           2625.0
Other potentially hazardous foods requiring coo...         419.0            743.0
Improperly functioning on-site sewage disposal ...         593.0           4966.0
Improper storage of cleaning equipment, linens,...         856.0           6943.0
Dressing rooms dirty, not provided, improperly ...         914.0           7659.0
Prepared food products contact equipment or wor...        1032.0           2812.0
Home canned goods, or canned goods from unappro...        1040.0           2773.0
All poultry, poultry stuffings, stuffed meats a...        1093.0           2391.0
Cracked/dirty fresh eggs, liquid or frozen eggs...        1171.0           3545.0
Foods or food area/public area contamination by...        1188.0           3313.0
Food workers prepare raw and cooked or ready to...        1527.0           3337.0
Food workers do not wash hands thoroughly after...        1531.0           4519.0
Potentially hazardous foods such as salads prep...        1684.0           3260.0
Shellfish not from approved sources, improperly...        2452.0           7538.0
Precooked, refrigerated potentially hazardous f...        3153.0           7723.0
Adequate, leakproof, non-absorbent, vermin-proo...        3192.0          29743.0
Hair is improperly restrained                             3443.0          25207.0
Enough hot holding equipment is not present, pr...        4342.0           7482.0
Hot, cold running water not provided, pressure ...        4387.0          42445.0
Garbage storage areas not properly constructed ...        5089.0          47303.0
Water/ice: unsafe, unapproved sources, cross co...        5220.0          15053.0
Tobacco is used; eating, drinking in food prepa...        5630.0          37933.0
Premises littered, unnecessary equipment and ar...        6601.0          63117.0
Improper thawing procedures used                          6924.0          46129.0
Pesticide application not supervised by a certi...        7629.0          47669.0
Canned foods found in poor conditions (leakers,...        8883.0          26793.0
Improper use and storage of clean, sanitized eq...        9456.0          84464.0
Food workers do not use proper utensils to elim...       11509.0          30998.0
Food from unapproved source, spoiled, adulterat...       11747.0          39627.0
Single service items reused, improperly stored,...       11950.0          96473.0
Effective measures not used to control entrance...       12653.0         123543.0
Miscellaneous, Economic Violation, Choking Post...       13668.0         126378.0
Toilet facilities inadequate, inconvenient, dir...       14131.0         140214.0
In use food dispensing utensils improperly stored        14451.0         114434.0
Manual facilities inadequate, technique incorre...       15973.0         126445.0
Insects, rodents present                                 16826.0         152348.0
Accurate thermometers not available or used to ...       17195.0          40225.0
Potentially hazardous foods are not cooled by a...       18150.0          44744.0
Food (ice) contact surfaces are improperly desi...       18798.0         175720.0
Enough refrigerated storage equipment is not pr...       19286.0          39055.0
Plumbing and sinks not properly sized, installe...       19682.0         193372.0
Wiping cloths dirty, not stored properly in san...       21280.0         156798.0
Potentially hazardous foods are not kept at or ...       22419.0          49608.0
Potentially hazardous foods are not stored unde...       24426.0          63592.0
Accurate thermometers not available or used to ...       24925.0         210607.0
Cooked or prepared foods are subject to cross-c...       26869.0          81252.0
Food contact surfaces not washed, rinsed and sa...       27022.0         235393.0
Handwashing facilities inaccessible, improperly...       28196.0         241063.0
Toxic chemicals are improperly labeled, stored ...       30037.0          96810.0
Potentially hazardous foods are not kept at or ...       34191.0          78439.0
Non-food contact surfaces and equipment are imp...       36078.0         367937.0
Lighting and ventilation inadequate, fixtures n...       37148.0         387210.0
Non food contact surfaces of equipment not clean         42974.0         434763.0
Floors, walls, ceilings, not smooth, properly c...       51431.0         543364.0
Food not protected during storage, preparation,...       55356.0         462918.0

Maybe associated with accident:
- Floors, walls, ceilings, not smooth, properly constructed, in disrepair, dirty surfaces

Maybe associated with disease:
- Food not protected during storage, preparation, display, transportation and service, from potential sources of contamination (e.g., food uncovered, mislabeled, stored on floor, missing or inadequate sneeze guards, food containers double stacked)
- Non food contact surfaces of equipment not clean
- Handwashing facilities inaccessible, improperly located, dirty, in disrepair, improper fixtures, soap, and single service towels or hand drying devices missing
- Accurate thermometers not available or used to evaluate refrigerated or heated storage temperatures
- Food contact surfaces not washed, rinsed and sanitized after each use and following any time of operations when contamination may have occurred
- Potentially hazardous foods are not kept at or below 45oF during cold holding, except smoked fish not kept at or below 38oF during cold holding.
- Cooked or prepared foods are subject to cross-contamination from raw foods.
- Potentially hazardous foods are not cooled by an approved method where the food temperature can be reduced from 120oF to 70oF or less within two hours and 70oF to 45oF within four hours.
- Improper thawing procedures used

# Counties

62 counties

community_health_county: include more stuff

service_requests_county: only for NYC, can use replace to change Borough name in County name

In [50]:
community_health_county  = community_health['county_name'].unique()
print(len(community_health_county))
community_health_county

77

array(['Albany', 'Allegany', 'Bronx', 'Broome', 'Capital Region',
       'Cattaraugus', 'Cayuga', 'Central NY', 'Chautauqua', 'Chemung',
       'Chenango', 'Clinton', 'Columbia', 'Cortland', 'Delaware',
       'Dutchess', 'Erie', 'Essex', 'Finger Lakes', 'Franklin', 'Fulton',
       'Genesee', 'North Country', 'Greene', 'Hamilton', 'Herkimer',
       'Jefferson', 'Kings', 'Lewis', 'Livingston', 'Long Island',
       'Madison', 'Mid-Hudson', 'Mohawk Valley', 'Monroe', 'Montgomery',
       'Nassau', 'New York', 'New York City', 'New York State', 'Niagara',
       'Oneida', 'Onondaga', 'Ontario', 'Orange', 'Orleans', 'Oswego',
       'Otsego', 'Putnam', 'Queens', 'Rensselaer', 'Richmond', 'Rockland',
       'Saratoga', 'Schenectady', 'Schoharie', 'Schuyler', 'Seneca',
       'Southern Tier', 'St. Lawrence', 'Steuben', 'Suffolk', 'Sullivan',
       'Tioga', 'Tompkins', 'Tug Hill Seaway', 'Ulster', 'Warren',
       'Washington', 'Wayne', 'Westchester', 'Western NY', 'Wyoming',
       'Yates', 'Essex/Hamilton', 'Hamilton/Essex',
       'New York State (excluding NYC)'], dtype=object)

In [51]:
service_requests_county  = service_requests['borough'].unique()
print(len(service_requests_county))
service_requests_county

6

array(['BROOKLYN', 'MANHATTAN', 'QUEENS', 'BRONX', 'STATEN ISLAND',
       'Unspecified'], dtype=object)

In [60]:
demographics_county  = demographics['geography'].unique()
print(len(demographics_county))
demographics_county

63

array(['New York', 'Albany County, New York', 'Allegany County, New York',
       'Bronx County, New York', 'Broome County, New York',
       'Cattaraugus County, New York', 'Cayuga County, New York',
       'Chautauqua County, New York', 'Chemung County, New York',
       'Chenango County, New York', 'Clinton County, New York',
       'Columbia County, New York', 'Cortland County, New York',
       'Delaware County, New York', 'Dutchess County, New York',
       'Erie County, New York', 'Essex County, New York',
       'Franklin County, New York', 'Fulton County, New York',
       'Genesee County, New York', 'Greene County, New York',
       'Hamilton County, New York', 'Herkimer County, New York',
       'Jefferson County, New York', 'Kings County, New York',
       'Lewis County, New York', 'Livingston County, New York',
       'Madison County, New York', 'Monroe County, New York',
       'Montgomery County, New York', 'Nassau County, New York',
       'New York County, New York', 'Niagara County, New York',
       'Oneida County, New York', 'Onondaga County, New York',
       'Ontario County, New York', 'Orange County, New York',
       'Orleans County, New York', 'Oswego County, New York',
       'Otsego County, New York', 'Putnam County, New York',
       'Queens County, New York', 'Rensselaer County, New York',
       'Richmond County, New York', 'Rockland County, New York',
       'St. Lawrence County, New York', 'Saratoga County, New York',
       'Schenectady County, New York', 'Schoharie County, New York',
       'Schuyler County, New York', 'Seneca County, New York',
       'Steuben County, New York', 'Suffolk County, New York',
       'Sullivan County, New York', 'Tioga County, New York',
       'Tompkins County, New York', 'Ulster County, New York',
       'Warren County, New York', 'Washington County, New York',
       'Wayne County, New York', 'Westchester County, New York',
       'Wyoming County, New York', 'Yates County, New York'], dtype=object)

In [63]:
food_establishment_inspections_county  = food_establishment_inspections['county'].unique()
print(len(food_establishment_inspections_county))
food_establishment_inspections_county

55

array(['NIAGARA', 'PUTNAM', 'ROCKLAND', 'SENECA', 'TOMPKINS', 'ULSTER',
       'ONTARIO', 'FULTON', 'TIOGA', 'WESTCHESTER', 'ONONDAGA', 'NASSAU',
       'JEFFERSON', 'DUTCHESS', 'OSWEGO', 'CLINTON', 'ORANGE', 'BROOME',
       'GENESEE', 'ALBANY', 'CORTLAND', 'LEWIS', 'CHEMUNG', 'ST LAWRENCE',
       'ONEIDA', 'CHAUTAUQUA', 'CAYUGA', 'SCHENECTADY', 'SULLIVAN',
       'STEUBEN', 'MONROE', 'MADISON', 'WASHINGTON', 'SARATOGA',
       'ALLEGANY', 'FRANKLIN', 'HERKIMER', 'GREENE', 'ESSEX',
       'RENSSELAER', 'WARREN', 'COLUMBIA', 'LIVINGSTON', 'CATTARAUGUS',
       'CHENANGO', 'ORLEANS', 'YATES', 'WAYNE', 'HAMILTON', 'SCHOHARIE',
       'WYOMING', 'DELAWARE', 'OTSEGO', 'SCHUYLER', 'MONTGOMERY'],
      dtype=object)

In [64]:
community_health['county']= community_health['county_name'].str.replace('.','').str.upper()
print(len(community_health['county'].unique()))
community_health['county'].unique()

77

array(['ALBANY', 'ALLEGANY', 'BRONX', 'BROOME', 'CAPITAL REGION',
       'CATTARAUGUS', 'CAYUGA', 'CENTRAL NY', 'CHAUTAUQUA', 'CHEMUNG',
       'CHENANGO', 'CLINTON', 'COLUMBIA', 'CORTLAND', 'DELAWARE',
       'DUTCHESS', 'ERIE', 'ESSEX', 'FINGER LAKES', 'FRANKLIN', 'FULTON',
       'GENESEE', 'NORTH COUNTRY', 'GREENE', 'HAMILTON', 'HERKIMER',
       'JEFFERSON', 'KINGS', 'LEWIS', 'LIVINGSTON', 'LONG ISLAND',
       'MADISON', 'MID-HUDSON', 'MOHAWK VALLEY', 'MONROE', 'MONTGOMERY',
       'NASSAU', 'NEW YORK', 'NEW YORK CITY', 'NEW YORK STATE', 'NIAGARA',
       'ONEIDA', 'ONONDAGA', 'ONTARIO', 'ORANGE', 'ORLEANS', 'OSWEGO',
       'OTSEGO', 'PUTNAM', 'QUEENS', 'RENSSELAER', 'RICHMOND', 'ROCKLAND',
       'SARATOGA', 'SCHENECTADY', 'SCHOHARIE', 'SCHUYLER', 'SENECA',
       'SOUTHERN TIER', 'ST LAWRENCE', 'STEUBEN', 'SUFFOLK', 'SULLIVAN',
       'TIOGA', 'TOMPKINS', 'TUG HILL SEAWAY', 'ULSTER', 'WARREN',
       'WASHINGTON', 'WAYNE', 'WESTCHESTER', 'WESTERN NY', 'WYOMING',
       'YATES', 'ESSEX/HAMILTON', 'HAMILTON/ESSEX',
       'NEW YORK STATE (EXCLUDING NYC)'], dtype=object)

In [67]:
demographics['county']=demographics['geography'].str.replace(' County, New York','').str.upper().str.replace('.','')
print(len(demographics['county'].unique()))
demographics['county'].unique()

62

array(['NEW YORK', 'ALBANY', 'ALLEGANY', 'BRONX', 'BROOME', 'CATTARAUGUS',
       'CAYUGA', 'CHAUTAUQUA', 'CHEMUNG', 'CHENANGO', 'CLINTON',
       'COLUMBIA', 'CORTLAND', 'DELAWARE', 'DUTCHESS', 'ERIE', 'ESSEX',
       'FRANKLIN', 'FULTON', 'GENESEE', 'GREENE', 'HAMILTON', 'HERKIMER',
       'JEFFERSON', 'KINGS', 'LEWIS', 'LIVINGSTON', 'MADISON', 'MONROE',
       'MONTGOMERY', 'NASSAU', 'NIAGARA', 'ONEIDA', 'ONONDAGA', 'ONTARIO',
       'ORANGE', 'ORLEANS', 'OSWEGO', 'OTSEGO', 'PUTNAM', 'QUEENS',
       'RENSSELAER', 'RICHMOND', 'ROCKLAND', 'ST LAWRENCE', 'SARATOGA',
       'SCHENECTADY', 'SCHOHARIE', 'SCHUYLER', 'SENECA', 'STEUBEN',
       'SUFFOLK', 'SULLIVAN', 'TIOGA', 'TOMPKINS', 'ULSTER', 'WARREN',
       'WASHINGTON', 'WAYNE', 'WESTCHESTER', 'WYOMING', 'YATES'],
      dtype=object)

In [65]:
set(food_establishment_inspections_county)-set(community_health['county'].unique())

set()

In [68]:
set(food_establishment_inspections_county)-set(demographics['county'].unique())

set()

# Goal: 

correlate 

food poisonning health indicator: Salmonella, Shigella

inspections:
- Food not protected during storage, preparation, display, transportation and service, from potential sources of contamination (e.g., food uncovered, mislabeled, stored on floor, missing or inadequate sneeze guards, food containers double stacked)
- Non food contact surfaces of equipment not clean
- Handwashing facilities inaccessible, improperly located, dirty, in disrepair, improper fixtures, soap, and single service towels or hand drying devices missing
- Accurate thermometers not available or used to evaluate refrigerated or heated storage temperatures
- Food contact surfaces not washed, rinsed and sanitized after each use and following any time of operations when contamination may have occurred
- Potentially hazardous foods are not kept at or below 45oF during cold holding, except smoked fish not kept at or below 38oF during cold holding.
- Cooked or prepared foods are subject to cross-contamination from raw foods.
- Potentially hazardous foods are not cooled by an approved method where the food temperature can be reduced from 120oF to 70oF or less within two hours and 70oF to 45oF within four hours.
- Improper thawing procedures used

311-complaints:
- ...

# Merge

In [90]:
community_health_pivot = pd.pivot_table(community_health[(
    community_health['indicator']=='Salmonella incidence per 100,000')|(
    community_health['indicator']=='E. coli O157 incidence per 100,000')|(
    community_health['indicator']=='Shigella incidence per 100,000')], index='county',columns='indicator')[['event_count','precent_or_rate']]
community_health_pivot

                                       event_count                                                                                    precent_or_rate
indicator       E. coli O157 incidence per 100,000 Salmonella incidence per 100,000 Shigella incidence per 100,000 E. coli O157 incidence per 100,000 Salmonella incidence per 100,000 Shigella incidence per 100,000
county
ALBANY                                         7.0                             95.0                           26.0                                0.8                             10.3                            2.8
ALLEGANY                                       1.0                             22.0                            1.0                                0.7                             15.3                            0.7
BRONX                                          7.0                            607.0                          165.0                                0.2                             14.2                            3.9
BROOME                                         0.0                             63.0                            1.0                                0.0                             10.6                            0.2
CAPITAL REGION                                20.0                            311.0                           47.0                                0.7                             10.8                            1.6
CATTARAUGUS                                    2.0                             29.0                            0.0                                0.8                             12.2                            0.0
CAYUGA                                         1.0                             25.0                            7.0                                0.4                             10.5                            2.9
CENTRAL NY                                    15.0                            348.0                          330.0                                0.5                             11.3                           10.8
CHAUTAUQUA                                     3.0                             54.0                            2.0                                0.8                             13.5                            0.5
CHEMUNG                                        0.0                             51.0                            1.0                                0.0                             19.2                            0.4
CHENANGO                                       0.0                             18.0                            0.0                                0.0                             12.1                            0.0
CLINTON                                        0.0                             30.0                            2.0                                0.0                             12.3                            0.8
COLUMBIA                                       6.0                             23.0                            4.0                                3.2                             12.3                            2.1
CORTLAND                                       0.0                             24.0                            3.0                                0.0                             16.3                            2.0
DELAWARE                                       0.0                             16.0                            0.0                                0.0                             11.4                            0.0
DUTCHESS                                       4.0                            105.0                           14.0                                0.4                             11.8                            1.6
ERIE                                          18.0                            263.0                           20.0                                0.7                              9.5                            0.7
ESSEX                                          0.0                             15.0                            1.0                                0.0                             12.9                            0.9
FINGER LAKES                                  67.0                            468.0                          235.0                                1.7                             12.2                            6.1
FRANKLIN                                       3.0                             38.0                            1.0                                1.9                             24.6                            0.6
FULTON                                         0.0                             21.0                            0.0                                0.0                             12.8                            0.0
GENESEE                                        3.0                             23.0                            1.0                                1.7                             12.9                            0.6
GREENE                                         0.0                             20.0                            0.0                                0.0                             13.8                            0.0
HAMILTON                                       0.0                              0.0                            0.0                                0.0                              0.0                            0.0
HERKIMER                                       1.0                             10.0                            4.0                                0.5                              5.2                            2.1
JEFFERSON                                      3.0                             50.0                            3.0                                0.8                             13.9                            0.8
KINGS                                         11.0                           1117.0                          578.0                                0.1                             14.4                            7.4
LEWIS                                          0.0                             16.0                            7.0                                0.0                             19.6                            8.6
LIVINGSTON                                    15.0                             16.0                            4.0                                7.7                              8.2                            2.1
LONG ISLAND                                   31.0                           1033.0                          343.0                                0.4                             12.1                            4.0
MADISON                                        0.0                             27.0                            2.0                                0.0                             12.4                            0.9
MID-HUDSON                                    40.0                            934.0                          365.0                                0.6                             13.4                            5.2
MOHAWK VALLEY                                  6.0                             67.0                            9.0                                0.8                              8.5                            1.1
MONROE                                        32.0                            236.0                          164.0                                1.4                             10.5                            7.3
MONTGOMERY                                     2.0                              8.0                            3.0                                1.3                              5.3                            2.0
NASSAU                                        17.0                            433.0                          188.0                                0.4                             10.7                            4.6
NEW YORK                                      16.0                            620.0                          295.0                                0.3                             12.7                            6.0
NEW YORK CITY                                 45.0                           3302.0                         1314.0                                0.2                             13.1                            5.2
NEW YORK STATE                               282.0                           7317.0                         2696.0                                0.5                             12.4                            4.6
NIAGARA                                        9.0                             54.0                            2.0                                1.4                              8.4                            0.3
NORTH COUNTRY                                  9.0                            118.0                            6.0                                1.0                             12.9                            0.7
ONEIDA                                         5.0                             71.0                           11.0                                0.7                             10.1                            1.6
ONONDAGA                                       8.0                            169.0                          307.0                                0.6                             12.0                           21.9
ONTARIO                                        4.0                             43.0                           17.0                                1.2                             13.1                            5.2
ORANGE                                         8.0                            146.0                           56.0                                0.7                             13.0                            5.0
ORLEANS                                        0.0                             11.0                            2.0                                0.0                              8.7                            1.6
OSWEGO                                         1.0                             32.0                            0.0                                0.3                              8.8                            0.0
OTSEGO                                         1.0                             19.0                            2.0                                0.5                             10.3                            1.1
PUTNAM                                         1.0                             44.0                            5.0                                0.3                             14.7                            1.7
QUEENS                                         8.0                            826.0                          257.0                                0.1                             12.0                            3.7
RENSSELAER                                     2.0                             61.0                            6.0                                0.4                             12.7                            1.3
RICHMOND                                       3.0                            132.0                           19.0                                0.2                              9.3                            1.3
ROCKLAND                                       8.0                            152.0                          205.0                                0.8                             15.8                           21.3
SARATOGA                                       4.0                             65.0                            7.0                                0.6                              9.7                            1.0
SCHENECTADY                                    1.0                             47.0                            4.0                                0.2                             10.1                            0.9
SCHOHARIE                                      2.0                              9.0                            0.0                                2.1                              9.4                            0.0
SCHUYLER                                       0.0                             10.0                            1.0                                0.0                             18.0                            1.8
SENECA                                         0.0                             15.0                            1.0                                0.0                             14.2                            0.9
SOUTHERN TIER                                  2.0                            151.0                            8.0                                0.1                             11.2                            0.6
ST LAWRENCE                                    5.0                             46.0                            1.0                                1.5                             13.7                            0.3
STEUBEN                                        7.0                             41.0                            0.0                                2.4                             13.8                            0.0
SUFFOLK                                       14.0                            600.0                          155.0                                0.3                             13.3                            3.4
SULLIVAN                                       1.0                             37.0                            5.0                                0.4                             16.1                            2.2
TIOGA                                          1.0                             16.0                            0.0                                0.7                             10.6                            0.0
TOMPKINS                                       1.0                             38.0                            7.0                                0.3                             12.2                            2.3
TUG HILL SEAWAY                                8.0                            112.0                           11.0                                1.0                             14.4                            1.4
ULSTER                                         2.0                             56.0                            8.0                                0.4                             10.3                            1.5
WARREN                                         3.0                             16.0                            2.0                                1.5                              8.2                            1.0
WASHINGTON                                     3.0                             19.0                            0.0                                1.6                             10.1                            0.0
WAYNE                                          7.0                             43.0                           43.0                                2.5                             15.5                           15.5
WESTCHESTER                                   16.0                            394.0                           72.0                                0.6                             13.6                            2.5
WESTERN NY                                    39.0                            473.0                           28.0                                0.8                             10.2                            0.6
WYOMING                                        3.0                             17.0                            0.0                                2.4                             13.6                            0.0
YATES                                          2.0                             13.0                            4.0                                2.6                             17.2                            5.3

In [96]:
food_establishment_inspections_county = food_establishment_inspections.groupby('county')['num_critical','num_noncritical'].sum()
food_establishment_inspections_county

             num_critical  num_noncritical
county
ALBANY            12528.0         123213.0
ALLEGANY           1843.0           7795.0
BROOME            16326.0         202304.0
CATTARAUGUS        2293.0          10808.0
CAYUGA              948.0           8026.0
CHAUTAUQUA         6511.0          43768.0
CHEMUNG            6779.0          23744.0
CHENANGO           1252.0           6559.0
CLINTON           11304.0          40394.0
COLUMBIA           1900.0          15347.0
CORTLAND           6128.0          46935.0
DELAWARE           3108.0          28250.0
DUTCHESS          18857.0          89563.0
ESSEX             22702.0         122958.0
FRANKLIN           7717.0          50213.0
FULTON             1902.0          10401.0
GENESEE            7187.0          38739.0
GREENE             7306.0          60270.0
HAMILTON           5208.0          31929.0
HERKIMER           1646.0          10315.0
JEFFERSON         16592.0         125264.0
LEWIS              2810.0          23066.0
LIVINGSTON          971.0           3632.0
MADISON            3872.0          29693.0
MONROE            51691.0         395460.0
MONTGOMERY         1621.0           8056.0
NASSAU           121803.0         825215.0
NIAGARA           20840.0          78642.0
ONEIDA             3067.0          14953.0
ONONDAGA          91714.0         515346.0
ONTARIO            9965.0          46406.0
ORANGE            21772.0         101423.0
ORLEANS            3468.0           9582.0
OSWEGO             5382.0          26269.0
OTSEGO             4865.0          32765.0
PUTNAM             3449.0          38377.0
RENSSELAER         4777.0           8762.0
ROCKLAND          13457.0          83731.0
SARATOGA          39785.0         212913.0
SCHENECTADY        9136.0          30110.0
SCHOHARIE          1959.0          16536.0
SCHUYLER            539.0           3161.0
SENECA             3735.0           9928.0
ST LAWRENCE       15852.0         176667.0
STEUBEN            2773.0          18653.0
SULLIVAN          24259.0         153418.0
TIOGA              1469.0           9081.0
TOMPKINS           3154.0           4390.0
ULSTER            11865.0         183353.0
WARREN            34888.0         184636.0
WASHINGTON         6754.0          39763.0
WAYNE              4424.0          24184.0
WESTCHESTER       83254.0         983166.0
WYOMING             661.0           5254.0
YATES               948.0           7973.0

In [97]:
demographics_county = demographics.groupby('county').mean()
demographics_county

               year  total_households  $9,999_or_less  $10,000_to_$14,999  $15,000_to_$24,999  $25,000_to_$34,999  $35,000_to_$49,999  $50,000_to_$74,999  $75,000_to_$99,999  $100,000_to_$150,000           ...             mean_soc_sec  mean_ret_income  mean_supp_sec_income  mean_cash_pub_income  food_stamp_benefits  population  pop_w_health_insurance  pop_w_private_health  pop_w_public_coverage  pop_no_health_insurance
county                                                                                                                                                                                                        ...
ALBANY       2013.5      1.232370e+05     7956.666667         6230.166667        11382.833333        10853.166667        15492.666667        22499.500000        16237.500000          18984.500000           ...             18274.500000     28040.166667           9281.166667           4248.000000         12708.333333    302562.6                282994.0              235696.4                88388.2                  19568.6
ALLEGANY     2013.5      1.854817e+04     1337.500000         1332.500000         2493.333333         2338.500000         3231.666667         3581.500000         2128.333333           1553.833333           ...             16991.333333     18400.166667           9286.166667           3773.166667          2968.166667     47840.4                 43365.6               33021.8                17663.6                   4474.8
BRONX        2013.5      4.793352e+05    76498.000000        43891.333333        67483.500000        53833.666667        64334.333333        72933.666667        42688.500000          38113.000000           ...             13704.666667     19872.000000           8615.166667           3456.666667        169468.166667   1389130.2               1189392.0              601694.6               706861.2                 199738.2
BROOME       2013.5      7.959183e+04     6628.500000         4991.500000        10395.500000         8812.500000        11624.000000        14722.833333         9014.000000           8671.166667           ...             17577.500000     20982.833333           8975.166667           3861.333333         11430.833333    195789.8                180674.0              136543.8                73245.4                  15115.8
CATTARAUGUS  2013.5      3.200667e+04     2177.000000         2298.166667         4610.333333         3981.666667         5070.500000         6392.500000         3715.166667           2769.333333           ...             16817.833333     18379.500000           9108.166667           3212.500000          4893.333333     78579.2                 70045.4               53347.0                30123.8                   8533.8
CAYUGA       2013.5      3.124383e+04     1874.666667         1569.166667         3777.333333         3301.500000         4598.666667         6545.666667         4153.500000           3871.833333           ...             17224.333333     19548.166667           9616.500000           3174.666667          3630.666667     76050.2                 68980.8               53784.0                27033.4                   7069.4
CHAUTAUQUA   2013.5      5.430033e+04     4841.500000         3897.333333         7465.333333         6606.500000         8595.333333        10181.166667         6161.000000           4662.166667           ...             16932.166667     19784.833333           9508.500000           3764.833333          9188.166667    130653.2                119792.0               87442.4                52781.4                  10861.2
CHEMUNG      2013.5      3.534100e+04     2643.333333         2216.333333         4709.500000         3913.000000         4566.500000         6954.833333         4099.000000           4105.833333           ...             17175.833333     19352.833333           9474.000000           3493.833333          5254.000000     84384.2                 78100.2               58588.4                32314.2                   6284.0
CHENANGO     2013.5      1.977483e+04     1439.166667         1319.833333         2631.333333         2325.833333         3130.000000         3924.666667         2446.166667           1853.666667           ...             17063.333333     17296.166667           9762.000000           3151.166667          3118.666667     49274.4                 44794.6               32590.4                19888.2                   4479.8
CLINTON      2013.5      3.179500e+04     2284.833333         1967.333333         3715.500000         3489.500000         4375.000000         6320.333333         3972.000000           3936.500000           ...             17173.500000     22655.333333          10129.166667           3393.333333          5224.833333     77252.8                 72270.0               56903.2                27595.8                   4982.8
COLUMBIA     2013.5      2.534367e+04     1272.666667         1104.833333         2544.333333         2692.833333         3400.333333         4629.833333         3450.333333           3848.666667           ...             18177.333333     24626.833333           8764.666667           3586.666667          2235.500000     60567.6                 55792.4               44389.0                21359.8                   4775.2
CORTLAND     2013.5      1.790933e+04     1320.833333         1091.500000         2004.333333         1895.333333         2951.000000         3441.333333         2256.500000           1875.333333           ...             16552.833333     19105.166667           9188.166667           3445.833333          2491.000000     48654.0                 45117.0               36300.0                15172.2                   3537.0
DELAWARE     2013.5      1.956500e+04     1435.166667         1427.833333         2718.166667         2296.666667         2976.000000         3850.666667         2307.833333           1989.166667           ...             17403.500000     20433.833333           8650.166667           2752.666667          2384.500000     46629.6                 42235.0               31920.0                18691.4                   4394.6
DUTCHESS     2013.5      1.072222e+05     4759.666667         4155.333333         8233.833333         8597.000000        11373.666667        18596.833333        15582.500000          19710.666667           ...             19355.166667     27146.833333           9932.666667           4610.333333          9173.000000    289214.2                265359.4              222844.4                80516.6                  23854.8
ERIE         2013.5      3.811768e+05    32121.833333        22170.666667        43439.833333        39478.333333        50654.166667        68821.666667        47568.833333          48690.666667           ...             17590.500000     21431.500000           9442.333333           3712.500000         57602.000000    908670.8                853011.8              660781.6               323779.0                  55659.0
ESSEX        2013.5      1.572017e+04      852.333333          871.666667         1749.333333         1808.333333         2642.833333         3205.833333         2010.833333           1693.666667           ...             17825.333333     21536.333333          10218.000000           3202.833333          1611.666667     36671.4                 33472.2               26010.8                14108.6                   3199.2
FRANKLIN     2013.5      1.915433e+04     1750.333333         1338.000000         2354.666667         2086.333333         2679.000000         3636.500000         2569.833333           1995.500000           ...             16844.333333     23738.833333           8908.666667           4138.166667          3066.833333     46382.6                 41363.6               30236.2                18102.6                   5019.0
FULTON       2013.5      2.253867e+04     1790.333333         1401.333333         2854.000000         2628.500000         3538.333333         4435.000000         2502.000000           2550.333333           ...             16565.833333     20867.500000           8898.000000           2867.000000          3481.500000     53822.2                 48547.4               34835.0                22373.0                   5274.8
GENESEE      2013.5      2.392350e+04     1400.666667         1324.833333         2502.333333         2756.166667         3698.000000         4940.666667         3293.000000           2878.166667           ...             18028.000000     20417.500000           9809.333333           3839.000000          2510.166667     58980.2                 54246.2               43688.2                19520.0                   4734.0
GREENE       2013.5      1.809317e+04     1147.166667         1046.500000         2240.166667         2014.666667         2761.333333         3368.833333         2225.833333           2283.333333           ...             17839.500000     25242.500000          10294.833333           4524.000000          1713.333333     45542.4                 41673.2               32267.6                16778.4                   3869.2
HAMILTON     2013.5      1.757500e+03      100.000000           86.833333          191.666667          209.833333          269.833333          380.833333          202.500000            205.166667           ...             18379.833333     25561.500000          11055.833333           3772.166667            87.000000      4755.6                  4338.6                3607.6                 1797.8                    417.0
HERKIMER     2013.5      2.640717e+04     1851.333333         1946.166667         3257.500000         3122.000000         4151.666667         5250.333333         3372.500000           2480.000000           ...             16578.333333     18256.500000           9041.833333           4284.000000          4489.500000     63459.6                 57716.8               41678.2                25631.0                   5742.8
JEFFERSON    2013.5      4.457517e+04     3123.333333         2614.166667         4912.666667         5187.500000         7498.833333         9297.000000         5435.333333           4627.500000           ...             16506.666667     21232.000000           8901.000000           3814.666667          6910.333333    106101.8                 96872.6               73951.2                37627.4                   9229.2
KINGS        2013.5      9.219608e+05   106959.666667        63052.166667       104956.666667        91194.500000       115345.333333       147750.166667        96804.666667         107109.666667           ...             14843.833333     21317.166667           9001.666667           4154.833333        210851.833333   2554268.8               2231080.6             1322899.8              1087679.6                 323188.2
LEWIS        2013.5      1.058467e+04      701.500000          543.666667         1222.500000         1356.000000         1788.000000         2134.666667         1304.833333           1123.833333           ...             17156.000000     18864.166667           9580.333333           2931.500000          1625.166667     26744.8                 23983.0               18457.0                 9371.0                   2761.8
LIVINGSTON   2013.5      2.418417e+04     1560.833333         1220.666667         2555.666667         2494.000000         3479.666667         4829.500000         3656.666667           3274.333333           ...             17905.833333     21679.166667          10058.833333           3234.166667          2766.000000     62378.6                 58592.2               48691.0                19136.0                   3786.4
MADISON      2013.5      2.648733e+04     1622.166667         1227.166667         2624.166667         2719.000000         4088.333333         5467.000000         3660.833333           3362.000000           ...             17915.166667     21578.833333           9501.833333           4987.000000          2932.500000     71901.2                 67102.4               54026.4                22694.8                   4798.8
MONROE       2013.5      2.973063e+05    23791.166667        15027.833333        31380.000000        31050.833333        40490.333333        53445.833333        38290.166667          38946.000000           ...             18364.333333     21308.500000           9660.333333           3995.833333         40464.166667    740249.2                692676.8              548032.0               245799.4                  47572.4
MONTGOMERY   2013.5      1.973233e+04     1611.166667         1383.166667         2745.666667         2202.666667         2987.500000         3673.166667         2306.333333           2009.500000           ...             16445.166667     19431.333333           9095.666667           3975.333333          3566.166667     49113.4                 44152.2               30686.0                20783.8                   4961.2
NASSAU       2013.5      4.418202e+05    13305.666667        10392.666667        25147.500000        24375.833333        36348.500000        59075.500000        55297.833333          91217.166667           ...             20569.833333     32750.000000          10790.500000           5477.166667         20600.166667   1338588.4               1230700.2             1067543.4               328341.6                 107888.2
NEW YORK     2013.5      3.993494e+06   317898.416667       208933.333333       387507.583333       351703.416667       461222.416667       649443.500000       470728.083333         564655.166667           ...             17059.166667     27853.833333           8756.500000           3966.083333        570553.583333  10462238.5               9395412.7             6924927.0              3602758.0                1066825.8
NIAGARA      2013.5      8.820067e+04     6472.666667         5245.333333        10832.000000        10248.166667        12398.500000        16667.500000        10675.500000          10761.333333           ...             17818.166667     20009.500000           9396.833333           4155.166667         12110.833333    212552.4                197822.2              156350.6                77189.8                  14730.2
ONEIDA       2013.5      9.101133e+04     6972.500000         5525.666667        11092.666667        10148.333333        12626.666667        17723.833333        11003.166667          10527.666667           ...             16590.833333     22333.166667           8923.333333           3682.333333         14724.833333    225382.6                210019.6              153253.2                91318.2                  15363.0
ONONDAGA     2013.5      1.846545e+05    14312.500000        10059.500000        18894.000000        18260.166667        24186.333333        34191.500000        22942.333333          25999.666667           ...             18002.666667     22667.166667           9386.166667           3591.000000         24320.000000    462222.0                427648.2              339777.2               152759.4                  34573.8
ONTARIO      2013.5      4.395333e+04     1732.000000         1911.833333         4730.666667         4579.166667         6057.000000         8932.833333         5937.666667           6460.833333           ...             18638.000000     22234.000000           9489.166667           4101.666667          4054.000000    107735.4                 99791.6               82435.2                34049.4                   7943.8
ORANGE       2013.5      1.251252e+05     6285.333333         5161.000000        10048.166667         9674.000000        13343.833333        21071.833333        16885.333333          23952.166667           ...             18539.000000     28583.666667           9696.166667           4425.500000         12598.833333    364526.4                332404.6              262991.0               109210.2                  32121.8
ORLEANS      2013.5      1.592233e+04      946.000000          964.666667         2066.166667         1816.000000         2410.166667         3371.833333         2022.833333           1752.833333           ...             17632.500000     19426.666667          10106.166667           3051.500000          2582.333333     39672.4                 35955.2               27413.0                15609.8                   3717.2
OSWEGO       2013.5      4.544200e+04     3612.166667         2469.333333         5193.833333         5360.333333         6933.833333         8687.500000         5903.000000           5160.833333           ...             17401.000000     20539.833333           9031.666667           3888.500000          7034.833333    120598.6                110881.8               80470.0                46847.8                   9716.8
OTSEGO       2013.5      2.405083e+04     1760.333333         1468.333333         2926.500000         2842.666667         3544.833333         4961.166667         2777.833333           2539.333333           ...             17169.000000     23259.833333           9368.666667           2720.000000          2440.833333     61010.8                 56140.0               43854.4                21445.8                   4870.8
PUTNAM       2013.5      3.448967e+04      904.166667          714.666667         1891.166667         2301.333333         2691.666667         4786.833333         4751.333333           7776.166667           ...             20779.166667     29915.166667          11105.833333           6651.500000          1242.333333     98969.6                 90919.0               81482.6                21199.6                   8050.6
QUEENS       2013.5      7.780147e+05    55056.000000        35696.666667        77912.500000        73208.166667        99523.166667       141233.166667       101796.166667         114053.500000           ...             16408.500000     22966.500000           8678.666667           4117.166667        104845.333333   2261694.2               1892260.6             1238274.6               828621.4                 369433.6
RENSSELAER   2013.5      6.380250e+04     3818.666667         3073.000000         5805.833333         6009.833333         8254.000000        12029.000000         8802.833333          10332.500000           ...             17545.333333     26909.833333           9343.500000           3368.666667          7227.500000    157805.4                148045.0              120625.2                49148.8                   9760.4
RICHMOND     2013.5      1.648180e+05    11338.833333         6304.166667        12812.166667        11680.000000        16161.833333        25821.166667        22944.833333          30815.500000           ...             18516.333333     30628.833333           9504.333333           4013.166667         19030.666667    466857.0                432334.2              332106.0               143413.0                  34522.8
ROCKLAND     2013.5      9.851183e+04     3808.500000         3720.000000         7574.666667         6058.000000         8878.833333        13651.666667        12725.666667          18838.666667           ...             20655.833333     33649.000000           9987.666667           5269.666667          9498.166667    315078.4                285936.4              214847.8               106510.6                  29142.0
SARATOGA     2013.5      8.914450e+04     3185.000000         3120.333333         6630.000000         7094.166667        10189.000000        17285.833333        13339.666667          17123.333333           ...             19174.166667     26774.000000           9862.500000           3295.666667          6101.000000    219112.6                206767.0              181363.4                56308.6                  12345.6

In [98]:
merge_df = food_establishment_inspections_county.join(community_health_pivot).join(demographics_county)
merge_df

C:\Users\nicol\Anaconda3\lib\site-packages\pandas\core\reshape\merge.py:558: UserWarning: merging between different levels can give an unintended result (1 levels on the left, 2 on the right)
  warnings.warn(msg, UserWarning)

             num_critical  num_noncritical  (event_count, E. coli O157 incidence per 100,000)  (event_count, Salmonella incidence per 100,000)  (event_count, Shigella incidence per 100,000)  (precent_or_rate, E. coli O157 incidence per 100,000)  (precent_or_rate, Salmonella incidence per 100,000)  (precent_or_rate, Shigella incidence per 100,000)    year  total_households           ...             mean_soc_sec  mean_ret_income  mean_supp_sec_income  mean_cash_pub_income  food_stamp_benefits  population  pop_w_health_insurance  pop_w_private_health  pop_w_public_coverage  pop_no_health_insurance
county                                                                                                                                                                                                                                                                                                                                                                                           ...
ALBANY            12528.0         123213.0                                                7.0                                             95.0                                           26.0                                                0.8                                                   10.3                                                  2.8  2013.5     123237.000000           ...             18274.500000     28040.166667           9281.166667           4248.000000         12708.333333    302562.6                282994.0              235696.4                88388.2                  19568.6
ALLEGANY           1843.0           7795.0                                                1.0                                             22.0                                            1.0                                                0.7                                                   15.3                                                  0.7  2013.5      18548.166667           ...             16991.333333     18400.166667           9286.166667           3773.166667          2968.166667     47840.4                 43365.6               33021.8                17663.6                   4474.8
BROOME            16326.0         202304.0                                                0.0                                             63.0                                            1.0                                                0.0                                                   10.6                                                  0.2  2013.5      79591.833333           ...             17577.500000     20982.833333           8975.166667           3861.333333         11430.833333    195789.8                180674.0              136543.8                73245.4                  15115.8
CATTARAUGUS        2293.0          10808.0                                                2.0                                             29.0                                            0.0                                                0.8                                                   12.2                                                  0.0  2013.5      32006.666667           ...             16817.833333     18379.500000           9108.166667           3212.500000          4893.333333     78579.2                 70045.4               53347.0                30123.8                   8533.8
CAYUGA              948.0           8026.0                                                1.0                                             25.0                                            7.0                                                0.4                                                   10.5                                                  2.9  2013.5      31243.833333           ...             17224.333333     19548.166667           9616.500000           3174.666667          3630.666667     76050.2                 68980.8               53784.0                27033.4                   7069.4
CHAUTAUQUA         6511.0          43768.0                                                3.0                                             54.0                                            2.0                                                0.8                                                   13.5                                                  0.5  2013.5      54300.333333           ...             16932.166667     19784.833333           9508.500000           3764.833333          9188.166667    130653.2                119792.0               87442.4                52781.4                  10861.2
CHEMUNG            6779.0          23744.0                                                0.0                                             51.0                                            1.0                                                0.0                                                   19.2                                                  0.4  2013.5      35341.000000           ...             17175.833333     19352.833333           9474.000000           3493.833333          5254.000000     84384.2                 78100.2               58588.4                32314.2                   6284.0
CHENANGO           1252.0           6559.0                                                0.0                                             18.0                                            0.0                                                0.0                                                   12.1                                                  0.0  2013.5      19774.833333           ...             17063.333333     17296.166667           9762.000000           3151.166667          3118.666667     49274.4                 44794.6               32590.4                19888.2                   4479.8
CLINTON           11304.0          40394.0                                                0.0                                             30.0                                            2.0                                                0.0                                                   12.3                                                  0.8  2013.5      31795.000000           ...             17173.500000     22655.333333          10129.166667           3393.333333          5224.833333     77252.8                 72270.0               56903.2                27595.8                   4982.8
COLUMBIA           1900.0          15347.0                                                6.0                                             23.0                                            4.0                                                3.2                                                   12.3                                                  2.1  2013.5      25343.666667           ...             18177.333333     24626.833333           8764.666667           3586.666667          2235.500000     60567.6                 55792.4               44389.0                21359.8                   4775.2
CORTLAND           6128.0          46935.0                                                0.0                                             24.0                                            3.0                                                0.0                                                   16.3                                                  2.0  2013.5      17909.333333           ...             16552.833333     19105.166667           9188.166667           3445.833333          2491.000000     48654.0                 45117.0               36300.0                15172.2                   3537.0
DELAWARE           3108.0          28250.0                                                0.0                                             16.0                                            0.0                                                0.0                                                   11.4                                                  0.0  2013.5      19565.000000           ...             17403.500000     20433.833333           8650.166667           2752.666667          2384.500000     46629.6                 42235.0               31920.0                18691.4                   4394.6
DUTCHESS          18857.0          89563.0                                                4.0                                            105.0                                           14.0                                                0.4                                                   11.8                                                  1.6  2013.5     107222.166667           ...             19355.166667     27146.833333           9932.666667           4610.333333          9173.000000    289214.2                265359.4              222844.4                80516.6                  23854.8
ESSEX             22702.0         122958.0                                                0.0                                             15.0                                            1.0                                                0.0                                                   12.9                                                  0.9  2013.5      15720.166667           ...             17825.333333     21536.333333          10218.000000           3202.833333          1611.666667     36671.4                 33472.2               26010.8                14108.6                   3199.2
FRANKLIN           7717.0          50213.0                                                3.0                                             38.0                                            1.0                                                1.9                                                   24.6                                                  0.6  2013.5      19154.333333           ...             16844.333333     23738.833333           8908.666667           4138.166667          3066.833333     46382.6                 41363.6               30236.2                18102.6                   5019.0
FULTON             1902.0          10401.0                                                0.0                                             21.0                                            0.0                                                0.0                                                   12.8                                                  0.0  2013.5      22538.666667           ...             16565.833333     20867.500000           8898.000000           2867.000000          3481.500000     53822.2                 48547.4               34835.0                22373.0                   5274.8
GENESEE            7187.0          38739.0                                                3.0                                             23.0                                            1.0                                                1.7                                                   12.9                                                  0.6  2013.5      23923.500000           ...             18028.000000     20417.500000           9809.333333           3839.000000          2510.166667     58980.2                 54246.2               43688.2                19520.0                   4734.0
GREENE             7306.0          60270.0                                                0.0                                             20.0                                            0.0                                                0.0                                                   13.8                                                  0.0  2013.5      18093.166667           ...             17839.500000     25242.500000          10294.833333           4524.000000          1713.333333     45542.4                 41673.2               32267.6                16778.4                   3869.2
HAMILTON           5208.0          31929.0                                                0.0                                              0.0                                            0.0                                                0.0                                                    0.0                                                  0.0  2013.5       1757.500000           ...             18379.833333     25561.500000          11055.833333           3772.166667            87.000000      4755.6                  4338.6                3607.6                 1797.8                    417.0
HERKIMER           1646.0          10315.0                                                1.0                                             10.0                                            4.0                                                0.5                                                    5.2                                                  2.1  2013.5      26407.166667           ...             16578.333333     18256.500000           9041.833333           4284.000000          4489.500000     63459.6                 57716.8               41678.2                25631.0                   5742.8
JEFFERSON         16592.0         125264.0                                                3.0                                             50.0                                            3.0                                                0.8                                                   13.9                                                  0.8  2013.5      44575.166667           ...             16506.666667     21232.000000           8901.000000           3814.666667          6910.333333    106101.8                 96872.6               73951.2                37627.4                   9229.2
LEWIS              2810.0          23066.0                                                0.0                                             16.0                                            7.0                                                0.0                                                   19.6                                                  8.6  2013.5      10584.666667           ...             17156.000000     18864.166667           9580.333333           2931.500000          1625.166667     26744.8                 23983.0               18457.0                 9371.0                   2761.8
LIVINGSTON          971.0           3632.0                                               15.0                                             16.0                                            4.0                                                7.7                                                    8.2                                                  2.1  2013.5      24184.166667           ...             17905.833333     21679.166667          10058.833333           3234.166667          2766.000000     62378.6                 58592.2               48691.0                19136.0                   3786.4
MADISON            3872.0          29693.0                                                0.0                                             27.0                                            2.0                                                0.0                                                   12.4                                                  0.9  2013.5      26487.333333           ...             17915.166667     21578.833333           9501.833333           4987.000000          2932.500000     71901.2                 67102.4               54026.4                22694.8                   4798.8
MONROE            51691.0         395460.0                                               32.0                                            236.0                                          164.0                                                1.4                                                   10.5                                                  7.3  2013.5     297306.333333           ...             18364.333333     21308.500000           9660.333333           3995.833333         40464.166667    740249.2                692676.8              548032.0               245799.4                  47572.4
MONTGOMERY         1621.0           8056.0                                                2.0                                              8.0                                            3.0                                                1.3                                                    5.3                                                  2.0  2013.5      19732.333333           ...             16445.166667     19431.333333           9095.666667           3975.333333          3566.166667     49113.4                 44152.2               30686.0                20783.8                   4961.2
NASSAU           121803.0         825215.0                                               17.0                                            433.0                                          188.0                                                0.4                                                   10.7                                                  4.6  2013.5     441820.166667           ...             20569.833333     32750.000000          10790.500000           5477.166667         20600.166667   1338588.4               1230700.2             1067543.4               328341.6                 107888.2
NIAGARA           20840.0          78642.0                                                9.0                                             54.0                                            2.0                                                1.4                                                    8.4                                                  0.3  2013.5      88200.666667           ...             17818.166667     20009.500000           9396.833333           4155.166667         12110.833333    212552.4                197822.2              156350.6                77189.8                  14730.2
ONEIDA             3067.0          14953.0                                                5.0                                             71.0                                           11.0                                                0.7                                                   10.1                                                  1.6  2013.5      91011.333333           ...             16590.833333     22333.166667           8923.333333           3682.333333         14724.833333    225382.6                210019.6              153253.2                91318.2                  15363.0
ONONDAGA          91714.0         515346.0                                                8.0                                            169.0                                          307.0                                                0.6                                                   12.0                                                 21.9  2013.5     184654.500000           ...             18002.666667     22667.166667           9386.166667           3591.000000         24320.000000    462222.0                427648.2              339777.2               152759.4                  34573.8
ONTARIO            9965.0          46406.0                                                4.0                                             43.0                                           17.0                                                1.2                                                   13.1                                                  5.2  2013.5      43953.333333           ...             18638.000000     22234.000000           9489.166667           4101.666667          4054.000000    107735.4                 99791.6               82435.2                34049.4                   7943.8

In [99]:
merge_df.to_csv('merged.csv')

# Food violation only

In [ ]:
# maybe not do that

type_food_violation = ['Food not protected during storage, preparation, display, transportation and service, from potential sources of contamination (e.g., food uncovered, mislabeled, stored on floor, missing or inadequate sneeze guards, food containers double stacked)',]

print(len(food_establishment_inspections))
food_violation = food_establishment_inspections[food_establishment_inspections['violation_description'] in type_food_violation]
print(len(food_violation))

In [100]:
# do pivot_table
food_establishment_inspections_pivot = food_establishment_inspections.pivot_table(index='county',columns='violation_description')[['num_critical','num_noncritical']]
food_establishment_inspections_pivot

                                                                                                                                                         num_critical                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...                                                                                                                                           num_noncritical
violation_description Accurate thermometers not available or used to evaluate potentially hazardous food temperatures during cooking, cooling, reheating and holding. Accurate thermometers not available or used to evaluate refrigerated or heated storage temperatures Acid foods are stored in containers or pipes that consist of toxic metals. Adequate, leakproof, non-absorbent, vermin-proof, covered containers not provided where needed All ground meat and foods containing ground meat are not heated to 158oF or above except by consumer request. All pork or any food containing pork is not heated to 150oF or above. All poultry, poultry stuffings, stuffed meats and stuffings containing meat are not heated to 165oF or above. All shell eggs or foods containing shell eggs are not heated to 145oF or above except by consumer request. App.5-D.3(b)  Well casing in good condition and more than 18" above grade. Canned foods found in poor conditions (leakers, severe dents, rusty, swollen cans)                   ...                    Toilet facilities inadequate, inconvenient, dirty, in disrepair, toilet paper missing, not self-closing doors, missing hand wash signs Toxic chemicals are improperly labeled, stored or used so that contamination of food can occur. Toxic items improperly stored or used [14-4.20(b)(4), 14-4.70(a)(b)(c)(d)] Unpasteurized milk and milk products used Unwrapped/potentially hazardous foods are reserved. Valid permit to operate, conspicuously posted {7-1.3(a), (g)} Water/ice: unsafe, unapproved sources, cross connections Whole frozen poultry or poultry breasts, other than a single portion, are being cooked frozen or partially thawed. Wiping cloths dirty, not stored properly in sanitizing solutions Wiping cloths improperly used [14-4.115]
county                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ...
ALBANY                                                          1.469194                                                                                                                                        0.268047                                                                                           16.000000                                                                   0.647059                                                                                       5.500000                                                                                                     16.000000                                                              2.130435                                                                                                           NaN                                                                                                        NaN                                                                   1.451613                                                   ...                                                              5.002268                                                                                                                               4.446154                                                                                             NaN                                                          3.200000                                                NaN                                                 NaN                                                      3.902655                                                      4.0                                                                                                           4.914498                                                    NaN
ALLEGANY                                                        1.045455                                                                                                                                        0.467949                                                                                                 NaN                                                                   0.000000                                                                                            NaN                                                                                                           NaN                                                              2.000000                                                                                                           NaN                                                                                                        NaN                                                                   2.285714                                                   ...                                                              4.391304                                                                                                                               2.027778                                                                                             NaN                                                          0.000000                                                NaN                                                 NaN                                                      2.500000                                                      NaN                                                                                                           4.875000                                                    NaN
BROOME                                                          1.504202                                                                                                                                        0.514379                                                                                            1.500000                                                                   0.249123                                                                                            NaN                                                                                                           NaN                                                              1.000000                                                                                                           NaN                                                                                                        NaN                                                                   1.707831                                                   ...                                                              5.993361                                                                                                                               9.169565                                                                                             NaN                                                               NaN                                                NaN                                                 NaN                                                      5.440000                                                      0.0                                                                                                           8.610586                                                    NaN
CATTARAUGUS                                                     1.567164                                                                                                                                        0.242991                                                                                                 NaN                                                                   0.357143                                                                                            NaN                                                                                                           NaN                                                              4.000000                                                                                                           NaN                                                                                                        NaN                                                                   1.272727                                                   ...                                                              3.106195                                                                                                                               4.015625                                                                                             NaN                                                               NaN                                                NaN                                                 NaN                                                      1.000000                                                      NaN                                                                                                           2.909774                                                    NaN
CAYUGA                                                          2.277778                                                                                                                                        0.513158                                                                                                 NaN                                                                   0.000000                                                                                       4.000000                                                                                                           NaN                                                              6.000000                                                                                                           NaN                                                                                                        NaN                                                                        NaN                                                   ...                                                              2.793103                                                                                                                               4.833333                                                                                             NaN                                                               NaN                                                NaN                                                 NaN                                                      2.000000                                                      NaN                                                                                                           3.471910                                                    NaN
CHAUTAUQUA                                                      1.477178                                                                                                                                        0.481352                                                                                            1.000000                                                                   0.950000                                                                                       1.500000                                                                                                      1.000000                                                              1.363636                                                                                                           NaN                                                                                                        NaN                                                                   2.277778                                                   ...                                                              4.264463                                                                                                                               4.000000                                                                                             NaN                                                               NaN                                           1.000000                                                 NaN                                                      3.708333                                                      NaN                                                                                                           4.173401                                                    NaN
CHEMUNG                                                         1.891473                                                                                                                                        0.714286                                                                                                 NaN                                                                   0.777778                                                                                       2.000000                                                                                                           NaN                                                              2.000000                                                                                                           NaN                                                                                                        NaN                                                                   1.475000                                                   ...                                                              3.526946                                                                                                                               3.636364                                                                                             NaN                                                               NaN                                                NaN                                                 NaN                                                      2.892857                                                      NaN                                                                                                           3.306604                                                    NaN
CHENANGO                                                        1.571429                                                                                                                                        0.442623                                                                                                 NaN                                                                   0.000000                                                                                            NaN                                                                                                           NaN                                                              4.000000                                                                                                           NaN                                                                                                        NaN                                                                   1.500000                                                   ...                                                              3.555556                                                                                                                               3.923077                                                                                             NaN                                                               NaN                                                NaN                                                 NaN                                                      1.769231                                                      NaN                                                                                                           3.266667                                                    2.0
CLINTON                                                         2.096859                                                                                                                                        0.892989                                                                                            3.000000                                                                   1.058824                                                                                       2.000000                                                                                                      1.000000                                                              2.666667                                                                                                           NaN                                                                                                        NaN                                                                   2.666667                                                   ...                                                              5.442029                                                                                                                               4.896104                                                                                             NaN                                                          5.500000                                          29.000000                                                 NaN                                                      3.450000                                                      2.0                                                                                                           4.162281                                                    NaN

# Look at corelations

In [ ]:
community_health_pivot = pd.pivot_table(community_health[(
    community_health['indicator']=='Salmonella incidence per 100,000')|(
    community_health['indicator']=='E. coli O157 incidence per 100,000')|(
    community_health['indicator']=='Shigella incidence per 100,000')], index='county',columns='indicator')[['event_count','precent_or_rate']]
community_health_pivot

# Use year (groupby county year) then look at trend